In [44]:
#!kaggle datasets download -d arashnic/baseballdatabank

import pandas as pd
import numpy as np

In [45]:
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)

In [46]:

hallOfFame = pd.read_csv("HallOfFame.csv", sep=",", header="infer")

hallOfFame.head()
type(hallOfFame['playerID'])
hallOfFame

       playerID  yearid   votedBy  ballots  needed  votes inducted           category needed_note
0     cobbty01   1936    BBWAA     226.0    170.0   222.0  Y        Player             NaN
1     ruthba01   1936    BBWAA     226.0    170.0   215.0  Y        Player             NaN
2     wagneho01  1936    BBWAA     226.0    170.0   215.0  Y        Player             NaN
3     mathech01  1936    BBWAA     226.0    170.0   205.0  Y        Player             NaN
4     johnswa01  1936    BBWAA     226.0    170.0   189.0  Y        Player             NaN
5     lajoina01  1936    BBWAA     226.0    170.0   146.0  N        Player             NaN
6     speaktr01  1936    BBWAA     226.0    170.0   133.0  N        Player             NaN
7     youngcy01  1936    BBWAA     226.0    170.0   111.0  N        Player             NaN
8     hornsro01  1936    BBWAA     226.0    170.0   105.0  N        Player             NaN
9     cochrmi01  1936    BBWAA     226.0    170.0   80.0   N        Player             NaN
10    sislege01  1936    BBWAA     226.0    170.0   77.0   N        Player             NaN
11    collied01  1936    BBWAA     226.0    170.0   60.0   N        Player             NaN
12    colliji01  1936    BBWAA     226.0    170.0   58.0   N        Player             NaN
13    alexape01  1936    BBWAA     226.0    170.0   55.0   N        Player             NaN
14    gehrilo01  1936    BBWAA     226.0    170.0   51.0   N        Player             NaN
15    bresnro01  1936    BBWAA     226.0    170.0   47.0   N        Player             NaN
16    keelewi01  1936    BBWAA     226.0    170.0   40.0   N        Player             NaN
17    ansonca01  1936    Veterans  78.0     59.0    39.0   N        Player             NaN
18    ewingbu01  1936    Veterans  78.0     59.0    39.0   N        Player             NaN
19    keelewi01  1936    Veterans  78.0     59.0    33.0   N        Player             NaN
20    wadderu01  1936    BBWAA     226.0    170.0   33.0   N        Player             NaN
21    youngcy01  1936    Veterans  78.0     59.0    32.0   N        Player             NaN
22    delahed01  1936    Veterans  78.0     59.0    21.0   N        Player             NaN
23    foxxji01   1936    BBWAA     226.0    170.0   21.0   N        Player             NaN
24    walshed01  1936    BBWAA     226.0    170.0   20.0   N        Player             NaN
25    mcgrajo01  1936    Veterans  78.0     59.0    17.0   N        Player             NaN
26    delahed01  1936    BBWAA     226.0    170.0   17.0   N        Player             NaN
27    radboch01  1936    Veterans  78.0     59.0    16.0   N        Player             NaN
28    traynpi01  1936    BBWAA     226.0    170.0   16.0   N        Player             NaN
29    kellyki01  1936    Veterans  78.0     59.0    15.0   N        Player             NaN
...         ...   ...         ...   ...      ...     ...  ..           ...             ...
4126  clemero02  2017    BBWAA     442.0    332.0   239.0  N        Player             NaN
4127  bondsba01  2017    BBWAA     442.0    332.0   238.0  N        Player             NaN
4128  mussimi01  2017    BBWAA     442.0    332.0   229.0  N        Player             NaN
4129  schilcu01  2017    BBWAA     442.0    332.0   199.0  N        Player             NaN
4130  smithle02  2017    BBWAA     442.0    332.0   151.0  N        Player             NaN
4131  ramirma02  2017    BBWAA     442.0    332.0   105.0  N        Player             NaN
4132  walkela01  2017    BBWAA     442.0    332.0   97.0   N        Player             NaN
4133  mcgrifr01  2017    BBWAA     442.0    332.0   96.0   N        Player             NaN
4134  kentje01   2017    BBWAA     442.0    332.0   74.0   N        Player             NaN
4135  sheffga01  2017    BBWAA     442.0    332.0   59.0   N        Player             NaN
4136  wagnebi02  2017    BBWAA     442.0    332.0   45.0   N        Player             NaN
4137  sosasa01   2017    BBWAA     442.0    332.0   38.0   N        Player             NaN
4138  posadjo01  2017    BBWAA     442.0    332.0   17.0   N        Player             NaN
4139  ordonma01  2017    BBWAA     442.0    332.0   3.0    N        Player             NaN
4140  varitja01  2017    BBWAA     442.0    332.0   2.0    N        Player             NaN
4141  renteed01  2017    BBWAA     442.0    332.0   2.0    N        Player             NaN
4142  wakefti01  2017    BBWAA     442.0    332.0   1.0    N        Player             NaN
4143  morame01   2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4144  camermi01  2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4145  rhodear01  2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4146  sanchfr01  2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4147  cabreor01  2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4148  drewj.01   2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4149  leede02    2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4150  blakeca01  2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4151  guillca01  2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4152  burrepa01  2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4153  stairma01  2017    BBWAA     442.0    332.0   0.0    N        Player             NaN
4154  seligbu99  2017    Veterans NaN      NaN     NaN     Y        Pioneer/Executive  NaN
4155  schurjo99  2017    Veterans NaN      NaN     NaN     Y        Pioneer/Executive  NaN

[4156 rows x 9 columns]

In [47]:
hallOfFame.shape

(4156, 9)

In [48]:
hallOfFame.describe().T

          count         mean         std     min     25%     50%     75%     max
yearid   4156.0  1969.306304  23.231639   1936.0  1950.0  1966.0  1988.0  2017.0
ballots  3961.0  321.746529   125.455368  78.0    226.0   274.0   427.0   581.0
needed   3804.0  244.776551   94.497219   59.0    175.0   213.0   323.0   436.0
votes    3961.0  51.465791    85.473954   0.0     2.0     10.0    64.0    555.0

In [49]:
hallOfFame.dtypes

playerID       object
yearid         int64
votedBy        object
ballots        float64
needed         float64
votes          float64
inducted       object
category       object
needed_note    object
dtype: object

In [50]:
cols_obj = [cols for cols in hallOfFame.columns if str(hallOfFame[cols].dtype)=="object" ]

cols_obj

hallOfFame[cols_obj].describe().T

            count unique        top  freq
playerID     4156  1260   roushed01  20
votedBy      4156  9      BBWAA      3723
inducted     4156  2      N          3839
category     4156  4      Player     4031
needed_note  157   2      1st        81

In [51]:
hallOfFame.isnull().sum()

playerID       0
yearid         0
votedBy        0
ballots        195
needed         352
votes          195
inducted       0
category       0
needed_note    3999
dtype: int64

In [52]:
batting = pd.read_csv("Batting.csv", header= "infer", sep=",")

batting.head()

    playerID  yearID  stint teamID lgID   G   AB   R   H  2B  3B  HR   RBI   SB   CS  BB   SO  IBB  HBP  SH  SF  GIDP
0  abercda01  1871    1      TRO    NaN  1   4    0   0   0   0   0   0.0   0.0  0.0  0   0.0 NaN  NaN  NaN NaN NaN
1  addybo01   1871    1      RC1    NaN  25  118  30  32  6   0   0   13.0  8.0  1.0  4   0.0 NaN  NaN  NaN NaN NaN
2  allisar01  1871    1      CL1    NaN  29  137  28  40  4   5   0   19.0  3.0  1.0  2   5.0 NaN  NaN  NaN NaN NaN
3  allisdo01  1871    1      WS3    NaN  27  133  28  44  10  2   2   27.0  1.0  1.0  0   2.0 NaN  NaN  NaN NaN NaN
4  ansonca01  1871    1      RC1    NaN  25  120  29  39  11  3   0   16.0  6.0  2.0  2   1.0 NaN  NaN  NaN NaN NaN

In [53]:
batting.shape

(102816, 22)

In [54]:
batting.describe().T

           count         mean         std     min     25%     50%     75%     max
yearID  102816.0  1964.262313  38.856297   1871.0  1934.0  1973.0  1998.0  2016.0
stint   102816.0  1.077838     0.284366    1.0     1.0     1.0     1.0     5.0
G       102816.0  51.343439    47.121658   1.0     13.0    34.0    80.0    165.0
AB      102816.0  141.905511   184.654492  0.0     4.0     49.0    231.0   716.0
R       102816.0  18.815544    28.242983   0.0     0.0     4.0     27.0    192.0
H       102816.0  37.139930    52.603757   0.0     0.0     9.0     58.0    262.0
2B      102816.0  6.289167     9.662468    0.0     0.0     1.0     9.0     67.0
3B      102816.0  1.293252     2.645770    0.0     0.0     0.0     1.0     36.0
HR      102816.0  2.813599     6.304919    0.0     0.0     0.0     2.0     73.0
RBI     102392.0  17.003975    26.352011   0.0     0.0     3.0     24.0    191.0
SB      101516.0  2.976821     7.717174    0.0     0.0     0.0     2.0     138.0
CS      79360.0   1.226008     2.747377    0.0     0.0     0.0     1.0     42.0
BB      102816.0  13.067207    20.746460   0.0     0.0     3.0     18.0    232.0
SO      94978.0   20.529712    28.328542   0.0     1.0     9.0     29.0    223.0
IBB     66251.0   1.105870     2.780187    0.0     0.0     0.0     1.0     120.0
HBP     100006.0  1.056057     2.276251    0.0     0.0     0.0     1.0     51.0
SH      96478.0   2.299540     4.241095    0.0     0.0     0.0     3.0     67.0
SF      66782.0   1.054101     1.961732    0.0     0.0     0.0     1.0     19.0
GIDP    76706.0   2.981018     4.735153    0.0     0.0     0.0     4.0     36.0

In [55]:
batting.dtypes

playerID    object
yearID      int64
stint       int64
teamID      object
lgID        object
G           int64
AB          int64
R           int64
H           int64
2B          int64
3B          int64
HR          int64
RBI         float64
SB          float64
CS          float64
BB          int64
SO          float64
IBB         float64
HBP         float64
SH          float64
SF          float64
GIDP        float64
dtype: object

In [56]:
cols_obj = [cols for cols in batting.columns if str(batting[cols].dtype)=="object" ]

cols_obj

batting[cols_obj].describe().T

           count unique        top   freq
playerID  102816  18915  mcguide01  31
teamID    102816  149    CHN        4863
lgID      102079  6      NL         52134

In [57]:
batting.isnull().sum()

playerID    0
yearID      0
stint       0
teamID      0
lgID        737
G           0
AB          0
R           0
H           0
2B          0
3B          0
HR          0
RBI         424
SB          1300
CS          23456
BB          0
SO          7838
IBB         36565
HBP         2810
SH          6338
SF          36034
GIDP        26110
dtype: int64

In [58]:
pitching = pd.read_csv("Pitching.csv", sep=",", header="infer")

pitching.head()

    playerID  yearID  stint teamID lgID   W   L   G  GS  CG  SHO  SV  IPouts    H   ER  HR  BB  SO  BAOpp    ERA  IBB  WP  HBP  BK  BFP  GF    R  SH  SF  GIDP
0  bechtge01  1871    1      PH1    NaN  1   2   3   3   2   0    0   78      43   23   0   11  1  NaN     7.96  NaN  NaN NaN   0  NaN  NaN  42  NaN NaN NaN
1  brainas01  1871    1      WS3    NaN  12  15  30  30  30  0    0   792     361  132  4   37  13 NaN     4.50  NaN  NaN NaN   0  NaN  NaN  292 NaN NaN NaN
2  fergubo01  1871    1      NY2    NaN  0   0   1   0   0   0    0   3       8    3    0   0   0  NaN     27.00 NaN  NaN NaN   0  NaN  NaN  9   NaN NaN NaN
3  fishech01  1871    1      RC1    NaN  4   16  24  24  22  1    0   639     295  103  3   31  15 NaN     4.35  NaN  NaN NaN   0  NaN  NaN  257 NaN NaN NaN
4  fleetfr01  1871    1      NY2    NaN  0   1   1   1   1   0    0   27      20   10   0   3   0  NaN     10.00 NaN  NaN NaN   0  NaN  NaN  21  NaN NaN NaN

In [59]:
pitching.shape

(44963, 30)

In [60]:
pitching.describe().T

          count         mean         std     min       25%      50%       75%      max
yearID  44963.0  1968.670062  37.569499   1871.0  1941.000  1978.00  2001.000  2016.00
stint   44963.0  1.079643     0.284834    1.0     1.000     1.00     1.000     4.00
W       44963.0  4.715744     5.813410    0.0     0.000     2.00     7.000     59.00
L       44963.0  4.715722     4.988846    0.0     1.000     3.00     8.000     48.00
G       44963.0  23.681761    18.493488   1.0     7.000     21.00    35.000    106.00
GS      44963.0  9.485488     12.283920   0.0     0.000     3.00     17.000    75.00
CG      44963.0  3.151035     7.081844    0.0     0.000     0.00     3.000     75.00
SHO     44963.0  0.448591     1.109742    0.0     0.000     0.00     0.000     16.00
SV      44963.0  1.504793     4.991518    0.0     0.000     0.00     1.000     62.00
IPouts  44963.0  253.872139   257.330446  0.0     49.000    167.00   393.000   2040.00
H       44963.0  84.912439    84.589269   0.0     18.000    55.00    134.000   772.00
ER      44963.0  36.103863    33.431186   0.0     9.000     25.00    58.000    291.00
HR      44963.0  6.434201     6.988237    0.0     1.000     4.00     9.000     50.00
BB      44963.0  29.905300    28.172268   0.0     8.000     21.00    45.000    289.00
SO      44963.0  46.500856    49.345046   0.0     8.000     31.00    68.000    513.00
BAOpp   43437.0  0.319920     0.710482    0.0     0.236     0.26     0.298     9.99
ERA     44874.0  5.073269     5.318781    0.0     3.150     4.14     5.510     189.00
IBB     30388.0  2.411379     2.772648    0.0     0.000     2.00     4.000     23.00
WP      44830.0  2.528575     3.425706    0.0     0.000     1.00     4.000     63.00
HBP     44405.0  2.266096     2.998881    0.0     0.000     1.00     3.000     41.00
BK      44963.0  0.301604     0.755523    0.0     0.000     0.00     0.000     16.00
BFP     44724.0  343.312181   348.758261  0.0     64.000    227.00   535.000   2906.00
GF      44830.0  6.345260     9.993949    0.0     0.000     3.00     8.000     84.00
R       44963.0  43.021773    43.245812   0.0     11.000    28.00    67.000    519.00
SH      12063.0  2.141922     2.710191    0.0     0.000     1.00     3.000     21.00
SF      12063.0  1.878388     2.121352    0.0     0.000     1.00     3.000     14.00
GIDP    12061.0  5.322610     5.990178    0.0     1.000     3.00     8.000     40.00

In [61]:
pitching.dtypes

playerID    object
yearID      int64
stint       int64
teamID      object
lgID        object
W           int64
L           int64
G           int64
GS          int64
CG          int64
SHO         int64
SV          int64
IPouts      int64
H           int64
ER          int64
HR          int64
BB          int64
SO          int64
BAOpp       float64
ERA         float64
IBB         float64
WP          float64
HBP         float64
BK          int64
BFP         float64
GF          float64
R           int64
SH          float64
SF          float64
GIDP        float64
dtype: object

In [62]:
cols_obj = [cols for cols in pitching.columns if str(pitching[cols].dtype) =="object"]

cols_obj

pitching[cols_obj].describe().T

          count unique        top   freq
playerID  44963  9302   newsobo01  29
teamID    44963  149    PHI        2117
lgID      44832  6      NL         22823

In [63]:
pitching.isnull().sum()

playerID    0
yearID      0
stint       0
teamID      0
lgID        131
W           0
L           0
G           0
GS          0
CG          0
SHO         0
SV          0
IPouts      0
H           0
ER          0
HR          0
BB          0
SO          0
BAOpp       1526
ERA         89
IBB         14575
WP          133
HBP         558
BK          0
BFP         239
GF          133
R           0
SH          32900
SF          32900
GIDP        32902
dtype: int64

In [64]:
batting

         playerID  yearID  stint teamID lgID    G   AB   R    H  2B  3B  HR   RBI    SB   CS  BB     SO  IBB  HBP   SH   SF  GIDP
0       abercda01  1871    1      TRO    NaN  1    4    0   0    0   0   0   0.0   0.0   0.0  0   0.0   NaN  NaN  NaN  NaN  NaN
1       addybo01   1871    1      RC1    NaN  25   118  30  32   6   0   0   13.0  8.0   1.0  4   0.0   NaN  NaN  NaN  NaN  NaN
2       allisar01  1871    1      CL1    NaN  29   137  28  40   4   5   0   19.0  3.0   1.0  2   5.0   NaN  NaN  NaN  NaN  NaN
3       allisdo01  1871    1      WS3    NaN  27   133  28  44   10  2   2   27.0  1.0   1.0  0   2.0   NaN  NaN  NaN  NaN  NaN
4       ansonca01  1871    1      RC1    NaN  25   120  29  39   11  3   0   16.0  6.0   2.0  2   1.0   NaN  NaN  NaN  NaN  NaN
5       armstbo01  1871    1      FW1    NaN  12   49   9   11   2   1   0   5.0   0.0   1.0  0   1.0   NaN  NaN  NaN  NaN  NaN
6       barkeal01  1871    1      RC1    NaN  1    4    0   1    0   0   0   2.0   0.0   0.0  1   0.0   NaN  NaN  NaN  NaN  NaN
7       barnero01  1871    1      BS1    NaN  31   157  66  63   10  9   0   34.0  11.0  6.0  13  1.0   NaN  NaN  NaN  NaN  NaN
8       barrebi01  1871    1      FW1    NaN  1    5    1   1    1   0   0   1.0   0.0   0.0  0   0.0   NaN  NaN  NaN  NaN  NaN
9       barrofr01  1871    1      BS1    NaN  18   86   13  13   2   1   0   11.0  1.0   0.0  0   0.0   NaN  NaN  NaN  NaN  NaN
10      bassjo01   1871    1      CL1    NaN  22   89   18  27   1   10  3   18.0  0.0   1.0  3   4.0   NaN  NaN  NaN  NaN  NaN
11      battijo01  1871    1      CL1    NaN  1    3    0   0    0   0   0   0.0   0.0   0.0  1   0.0   NaN  NaN  NaN  NaN  NaN
12      bealsto01  1871    1      WS3    NaN  10   36   6   7    0   0   0   1.0   2.0   0.0  2   0.0   NaN  NaN  NaN  NaN  NaN
13      beaveed01  1871    1      TRO    NaN  3    15   7   6    0   0   0   5.0   2.0   0.0  0   0.0   NaN  NaN  NaN  NaN  NaN
14      bechtge01  1871    1      PH1    NaN  20   94   24  33   9   1   1   21.0  4.0   0.0  2   2.0   NaN  NaN  NaN  NaN  NaN
15      bellast01  1871    1      TRO    NaN  29   128  26  32   3   3   0   23.0  4.0   4.0  9   2.0   NaN  NaN  NaN  NaN  NaN
16      berkena01  1871    1      PH1    NaN  1    4    0   0    0   0   0   0.0   0.0   0.0  0   3.0   NaN  NaN  NaN  NaN  NaN
17      berryto01  1871    1      PH1    NaN  1    4    0   1    0   0   0   0.0   0.0   0.0  0   0.0   NaN  NaN  NaN  NaN  NaN
18      berthha01  1871    1      WS3    NaN  17   73   17  17   1   1   0   8.0   3.0   1.0  4   2.0   NaN  NaN  NaN  NaN  NaN
19      biermch01  1871    1      FW1    NaN  1    2    0   0    0   0   0   0.0   0.0   0.0  1   0.0   NaN  NaN  NaN  NaN  NaN
20      birdge01   1871    1      RC1    NaN  25   106  19  28   2   5   0   13.0  1.0   0.0  3   2.0   NaN  NaN  NaN  NaN  NaN
21      birdsda01  1871    1      BS1    NaN  29   152  51  46   3   3   0   24.0  6.0   0.0  4   4.0   NaN  NaN  NaN  NaN  NaN
22      brainas01  1871    1      WS3    NaN  30   134  24  30   4   0   0   21.0  4.0   0.0  7   2.0   NaN  NaN  NaN  NaN  NaN
23      brannmi01  1871    1      CH1    NaN  3    14   2   1    0   0   0   0.0   0.0   0.0  0   0.0   NaN  NaN  NaN  NaN  NaN
24      burrohe01  1871    1      WS3    NaN  12   63   11  15   2   3   1   14.0  0.0   0.0  1   1.0   NaN  NaN  NaN  NaN  NaN
25      careyto01  1871    1      FW1    NaN  19   87   16  20   2   0   0   10.0  5.0   0.0  2   1.0   NaN  NaN  NaN  NaN  NaN
26      carleji01  1871    1      CL1    NaN  29   127  31  32   8   1   0   18.0  2.0   1.0  8   3.0   NaN  NaN  NaN  NaN  NaN
27      conefr01   1871    1      BS1    NaN  19   77   17  20   3   1   0   16.0  12.0  1.0  8   2.0   NaN  NaN  NaN  NaN  NaN
28      connone01  1871    1      TRO    NaN  7    33   6   7    0   0   0   2.0   0.0   0.0  0   0.0   NaN  NaN  NaN  NaN  NaN
29      cravebi01  1871    1      TRO    NaN  27   118  26  38   8   1   0   26.0  6.0   3.0  3   0.0   NaN  NaN  NaN  NaN  NaN
...           ...   ...   ..      ...    ...  ..   ...  ..  ..  ..  ..  ..    ...  ...   ... ..   ...    ..   ..   ..   ..   ..
102786  wittgni01  2016    1      MIA    NL   48   0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102787  wolteto01  2016    1      COL    NL   71   205  27  53   15  2   3   30.0  4.0   1.0  21  53.0   2.0  0.0  4.0  0.0  1.0
102788  wongko01   2016    1      SLN    NL   121  313  39  75   7   7   5   23.0  7.0   0.0  34  52.0   2.0  9.0  0.0  5.0  3.0
102789  woodal02   2016    1      LAN    NL   15   16   2   4    0   0   0   2.0   0.0   0.0  1   9.0    0.0  0.0  2.0  0.0  0.0
102790  woodbl01   2016    1      CIN    NL   70   2    0   0    0   0   0   0.0   0.0   0.0  0   2.0    0.0  0.0  0.0  0.0  0.0
102791  woodtr01   2016    1      CHN    NL   81   11   0   2    0   0   0   1.0   0.0   0.0  1   5.0    0.0  0.0  0.0  0.0  0.0
102792  worleva01  2016    1      BAL    AL   35   0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102793  worthda01  2016    1      HOU    AL   16   39   4   7    2   0   0   1.0   0.0   0.0  1   6.0    0.0  0.0  0.0  0.0  1.0
102794  wrighda03  2016    1      NYN    NL   37   137  18  31   8   0   7   14.0  3.0   2.0  26  55.0   0.0  0.0  0.0  0.0  0.0
102795  wrighda04  2016    1      CIN    NL   4    5    0   0    0   0   0   0.0   0.0   0.0  0   2.0    0.0  0.0  1.0  0.0  0.0
102796  wrighda04  2016    2      LAA    AL   5    0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102797  wrighmi01  2016    1      BAL    AL   18   0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102798  wrighst01  2016    1      BOS    AL   25   4    0   0    0   0   0   0.0   0.0   0.0  0   3.0    0.0  0.0  0.0  0.0  0.0
102799  yateski01  2016    1      NYA    AL   41   0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102800  yelicch01  2016    1      MIA    NL   155  578  78  172  38  3   21  98.0  9.0   4.0  72  138.0  4.0  4.0  0.0  5.0  20.0
102801  ynoaga01   2016    1      NYN    NL   10   3    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102802  ynoami01   2016    1      CHA    AL   23   0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102803  ynoara01   2016    1      COL    NL   3    5    0   0    0   0   0   0.0   0.0   0.0  0   2.0    0.0  0.0  0.0  0.0  0.0
102804  youngch03  2016    1      KCA    AL   34   1    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102805  youngch04  2016    1      BOS    AL   76   203  29  56   18  0   9   24.0  4.0   2.0  21  50.0   0.0  3.0  0.0  0.0  4.0
102806  younger03  2016    1      NYA    AL   6    1    2   0    0   0   0   0.0   1.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102807  youngma03  2016    1      ATL    NL   8    0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102808  zastrro01  2016    1      CHN    NL   8    3    0   0    0   0   0   0.0   0.0   0.0  0   2.0    0.0  0.0  0.0  0.0  0.0
102809  zieglbr01  2016    1      ARI    NL   36   0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102810  zieglbr01  2016    2      BOS    AL   33   0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0
102811  zimmejo02  2016    1      DET    AL   19   4    0   1    0   0   0   0.0   0.0   0.0  0   2.0    0.0  0.0  1.0  0.0  0.0
102812  zimmery01  2016    1      WAS    NL   115  427  60  93   18  1   15  46.0  4.0   1.0  29  104.0  1.0  5.0  0.0  6.0  12.0
102813  zobribe01  2016    1      CHN    NL   147  523  94  142  31  3   18  76.0  6.0   4.0  96  82.0   6.0  4.0  4.0  4.0  17.0
102814  zuninmi01  2016    1      SEA    AL   55   164  16  34   7   0   12  31.0  0.0   0.0  21  65.0   0.0  6.0  0.0  1.0  0.0
102815  zychto01   2016    1      SEA    AL   12   0    0   0    0   0   0   0.0   0.0   0.0  0   0.0    0.0  0.0  0.0  0.0  0.0

[102816 rows x 22 columns]

In [65]:
batting.isnull().sum()

playerID    0
yearID      0
stint       0
teamID      0
lgID        737
G           0
AB          0
R           0
H           0
2B          0
3B          0
HR          0
RBI         424
SB          1300
CS          23456
BB          0
SO          7838
IBB         36565
HBP         2810
SH          6338
SF          36034
GIDP        26110
dtype: int64

In [66]:
###################################################################################################################
###################################################################################################################
###################################################################################################################
###################################################################################################################
###################################################################################################################

In [67]:
battingdata = batting.groupby('playerID', as_index=False).sum()
battingdata.isnull().sum()
#batting.isnull().sum()

playerID    0
yearID      0
stint       0
G           0
AB          0
R           0
H           0
2B          0
3B          0
HR          0
RBI         0
SB          0
CS          0
BB          0
SO          0
IBB         0
HBP         0
SH          0
SF          0
GIDP        0
dtype: int64

In [68]:
battingdata.count()

playerID    18915
yearID      18915
stint       18915
G           18915
AB          18915
R           18915
H           18915
2B          18915
3B          18915
HR          18915
RBI         18915
SB          18915
CS          18915
BB          18915
SO          18915
IBB         18915
HBP         18915
SH          18915
SF          18915
GIDP        18915
dtype: int64

In [69]:
battingdata.head()

    playerID  yearID  stint     G     AB     R     H   2B  3B   HR     RBI     SB    CS    BB      SO    IBB   HBP    SH     SF   GIDP
0  aardsda01  18084   9      331   4      0     0     0    0   0    0.0     0.0    0.0   0     2.0     0.0    0.0   1.0   0.0    0.0
1  aaronha01  45195   23     3298  12364  2174  3771  624  98  755  2297.0  240.0  73.0  1402  1383.0  293.0  32.0  21.0  121.0  328.0
2  aaronto01  13768   7      437   944    102   216   42   6   13   94.0    9.0    8.0   86    145.0   3.0    0.0   9.0   6.0    36.0
3  aasedo01   25786   13     448   5      0     0     0    0   0    0.0     0.0    0.0   0     3.0     0.0    0.0   0.0   0.0    0.0
4  abadan01   6010    3      15    21     1     2     0    0   0    0.0     0.0    1.0   4     5.0     0.0    0.0   0.0   0.0    1.0

In [70]:
battingdata.describe().T

          count          mean          std     min     25%     50%      75%      max
yearID  18915.0  10677.113085  9959.489812  1871.0  2015.0  6042.0  15959.5  58823.0
stint   18915.0  5.858789      5.621206     1.0     1.0     4.0     9.0      39.0
G       18915.0  279.086809    453.824217   1.0     13.0    78.0    329.0    3562.0
AB      18915.0  771.353793    1603.985998  0.0     6.0     71.0    603.0    14053.0
R       18915.0  102.275390    238.578514   0.0     0.0     6.0     63.0     2295.0
H       18915.0  201.880994    450.549938   0.0     1.0     12.0    133.0    4256.0
2B      18915.0  34.185937     79.835905    0.0     0.0     2.0     21.0     792.0
3B      18915.0  7.029712      18.905794    0.0     0.0     0.0     4.0      309.0
HR      18915.0  15.293841     50.240622    0.0     0.0     0.0     4.0      762.0
RBI     18915.0  92.047105     222.361516   0.0     0.0     4.0     54.0     2297.0
SB      18915.0  15.976474     54.707079    0.0     0.0     0.0     5.0      1406.0
CS      18915.0  5.143854      16.352069    0.0     0.0     0.0     1.0      335.0
BB      18915.0  71.029236     175.079949   0.0     0.0     4.0     40.0     2558.0
SO      18915.0  103.085964    226.909601   0.0     1.0     11.0    89.0     2597.0
IBB     18915.0  3.873381      16.743993    0.0     0.0     0.0     0.0      688.0
HBP     18915.0  5.583505      15.570065    0.0     0.0     0.0     3.0      287.0
SH      18915.0  11.729051     28.469311    0.0     0.0     1.0     10.0     512.0
SF      18915.0  3.721649      12.085521    0.0     0.0     0.0     0.0      128.0
GIDP    18915.0  12.088924     33.423978    0.0     0.0     0.0     4.0      350.0

In [71]:
# Checking if playerID values appear uniquely

In [72]:
battingdata[battingdata['playerID']=='cobbty01']

      playerID  yearID  stint     G     AB     R     H   2B   3B   HR     RBI     SB     CS    BB     SO  IBB   HBP     SH   SF  GIDP
3155  cobbty01  45996   24     3035  11434  2246  4189  724  295  117  1937.0  892.0  178.0  1249  357.0  0.0  94.0  295.0  0.0  0.0

In [73]:
batting[batting['playerID']=='cobbty01']

       playerID  yearID  stint teamID lgID    G   AB    R    H  2B  3B  HR    RBI    SB    CS   BB    SO  IBB   HBP    SH  SF  GIDP
9840   cobbty01  1905    1      DET    AL   41   150  19   36   6   0   1   15.0   2.0  NaN    10  NaN   NaN   0.0   4.0  NaN NaN
10243  cobbty01  1906    1      DET    AL   98   358  45   113  15  5   1   34.0   23.0 NaN    19  NaN   NaN   3.0   14.0 NaN NaN
10699  cobbty01  1907    1      DET    AL   150  605  97   212  28  14  5   119.0  49.0 NaN    24  NaN   NaN   5.0   12.0 NaN NaN
11140  cobbty01  1908    1      DET    AL   150  581  88   188  36  20  4   108.0  39.0 NaN    34  NaN   NaN   6.0   14.0 NaN NaN
11627  cobbty01  1909    1      DET    AL   156  573  116  216  33  10  9   107.0  76.0 NaN    48  NaN   NaN   6.0   24.0 NaN NaN
12166  cobbty01  1910    1      DET    AL   140  506  106  194  35  13  8   91.0   65.0 NaN    64  NaN   NaN   4.0   16.0 NaN NaN
12708  cobbty01  1911    1      DET    AL   146  591  147  248  47  24  8   127.0  83.0 NaN    44  NaN   NaN   8.0   11.0 NaN NaN
13282  cobbty01  1912    1      DET    AL   140  553  120  226  30  23  7   83.0   61.0 NaN    43  NaN   NaN   5.0   8.0  NaN NaN
13921  cobbty01  1913    1      DET    AL   122  428  70   167  18  16  4   67.0   51.0 NaN    58   31.0 NaN   4.0   11.0 NaN NaN
14568  cobbty01  1914    1      DET    AL   98   345  69   127  22  11  2   57.0   35.0  17.0  57   22.0 NaN   6.0   6.0  NaN NaN
15352  cobbty01  1915    1      DET    AL   156  563  144  208  31  13  3   99.0   96.0  38.0  118  43.0 NaN   10.0  9.0  NaN NaN
16105  cobbty01  1916    1      DET    AL   145  542  113  201  31  10  5   68.0   68.0  24.0  78   39.0 NaN   2.0   14.0 NaN NaN
16653  cobbty01  1917    1      DET    AL   152  588  107  225  44  24  6   102.0  55.0 NaN    61   34.0 NaN   4.0   16.0 NaN NaN
17174  cobbty01  1918    1      DET    AL   111  421  83   161  19  14  3   64.0   34.0 NaN    41   21.0 NaN   2.0   9.0  NaN NaN
17680  cobbty01  1919    1      DET    AL   124  497  92   191  36  13  1   70.0   28.0 NaN    38   22.0 NaN   1.0   9.0  NaN NaN
18208  cobbty01  1920    1      DET    AL   112  428  86   143  28  8   2   63.0   15.0  10.0  58   28.0 NaN   2.0   7.0  NaN NaN
18721  cobbty01  1921    1      DET    AL   128  507  124  197  37  16  12  101.0  22.0  15.0  56   19.0 NaN   3.0   15.0 NaN NaN
19240  cobbty01  1922    1      DET    AL   137  526  99   211  42  16  4   99.0   9.0   13.0  55   24.0 NaN   4.0   27.0 NaN NaN
19763  cobbty01  1923    1      DET    AL   145  556  103  189  40  7   6   88.0   9.0   10.0  66   14.0 NaN   3.0   22.0 NaN NaN
20292  cobbty01  1924    1      DET    AL   155  625  115  211  38  10  4   78.0   23.0  14.0  85   18.0 NaN   1.0   15.0 NaN NaN
20841  cobbty01  1925    1      DET    AL   121  415  97   157  31  12  12  102.0  13.0  9.0   65   12.0 NaN   5.0   5.0  NaN NaN
21395  cobbty01  1926    1      DET    AL   79   233  48   79   18  5   4   62.0   9.0   4.0   26   2.0  NaN   1.0   13.0 NaN NaN
21935  cobbty01  1927    1      PHA    AL   134  490  104  175  32  7   5   93.0   22.0  16.0  67   12.0 NaN   5.0   12.0 NaN NaN
22476  cobbty01  1928    1      PHA    AL   95   353  54   114  27  4   1   40.0   5.0   8.0   34   16.0 NaN   4.0   2.0  NaN NaN

In [74]:
battingdata[battingdata['playerID']=='aardsda01']

    playerID  yearID  stint    G  AB  R  H  2B  3B  HR  RBI   SB   CS  BB   SO  IBB  HBP   SH   SF  GIDP
0  aardsda01  18084   9      331  4   0  0  0   0   0   0.0  0.0  0.0  0   2.0  0.0  0.0  1.0  0.0  0.0

In [75]:
batting[batting['playerID']=='aardsda01']

        playerID  yearID  stint teamID lgID   G  AB  R  H  2B  3B  HR  RBI   SB   CS  BB   SO  IBB  HBP   SH   SF  GIDP
84639  aardsda01  2004    1      SFN    NL   11  0   0  0  0   0   0   0.0  0.0  0.0  0   0.0  0.0  0.0  0.0  0.0  0.0
87315  aardsda01  2006    1      CHN    NL   45  2   0  0  0   0   0   0.0  0.0  0.0  0   0.0  0.0  0.0  1.0  0.0  0.0
88692  aardsda01  2007    1      CHA    AL   25  0   0  0  0   0   0   0.0  0.0  0.0  0   0.0  0.0  0.0  0.0  0.0  0.0
90077  aardsda01  2008    1      BOS    AL   47  1   0  0  0   0   0   0.0  0.0  0.0  0   1.0  0.0  0.0  0.0  0.0  0.0
91462  aardsda01  2009    1      SEA    AL   73  0   0  0  0   0   0   0.0  0.0  0.0  0   0.0  0.0  0.0  0.0  0.0  0.0
92850  aardsda01  2010    1      SEA    AL   53  0   0  0  0   0   0   0.0  0.0  0.0  0   0.0  0.0  0.0  0.0  0.0  0.0
95595  aardsda01  2012    1      NYA    AL   1   0   0  0  0   0   0   0.0  0.0  0.0  0   0.0  0.0  0.0  0.0  0.0  0.0
97003  aardsda01  2013    1      NYN    NL   43  0   0  0  0   0   0   0.0  0.0  0.0  0   0.0  0.0  0.0  0.0  0.0  0.0
99847  aardsda01  2015    1      ATL    NL   33  1   0  0  0   0   0   0.0  0.0  0.0  0   1.0  0.0  0.0  0.0  0.0  0.0

In [76]:
battingdata

        playerID  yearID  stint     G     AB     R     H   2B  3B   HR     RBI     SB    CS    BB      SO    IBB   HBP    SH     SF   GIDP
0      aardsda01  18084   9      331   4      0     0     0    0   0    0.0     0.0    0.0   0     2.0     0.0    0.0   1.0   0.0    0.0
1      aaronha01  45195   23     3298  12364  2174  3771  624  98  755  2297.0  240.0  73.0  1402  1383.0  293.0  32.0  21.0  121.0  328.0
2      aaronto01  13768   7      437   944    102   216   42   6   13   94.0    9.0    8.0   86    145.0   3.0    0.0   9.0   6.0    36.0
3      aasedo01   25786   13     448   5      0     0     0    0   0    0.0     0.0    0.0   0     3.0     0.0    0.0   0.0   0.0    0.0
4      abadan01   6010    3      15    21     1     2     0    0   0    0.0     0.0    1.0   4     5.0     0.0    0.0   0.0   0.0    1.0
5      abadfe01   16107   9      315   9      0     1     0    0   0    0.0     0.0    0.0   0     5.0     0.0    0.0   0.0   0.0    1.0
6      abadijo01  3750    3      12    49     4     11    0    0   0    5.0     1.0    0.0   0     3.0     0.0    0.0   0.0   0.0    0.0
7      abbated01  19051   11     855   3044   355   772   99   43  11   324.0   142.0  0.0   289   16.0    0.0    33.0  93.0  0.0    0.0
8      abbeybe01  11365   7      79    225    21    38    3    3   0    17.0    3.0    0.0   21    54.0    0.0    0.0   4.0   0.0    0.0
9      abbeych01  9475    5      451   1751   307   492   67   46  19   280.0   93.0   0.0   167   105.0   0.0    23.0  18.0  0.0    0.0
10     abbotda01  1890    1      3     7      0     1     0    1   0    1.0     1.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0
11     abbotfr01  5712    3      160   513    48    107   21   6   1    49.0    14.0   0.0   19    0.0     0.0    8.0   20.0  0.0    0.0
12     abbotgl01  23743   13     248   0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0
13     abbotje01  9995    5      233   596    82    157   33   2   18   83.0    6.0    5.0   38    91.0    2.0    3.0   5.0   7.0    12.0
14     abbotji01  21932   12     263   21     0     2     0    0   0    3.0     0.0    0.0   0     10.0    0.0    0.0   3.0   0.0    1.0
15     abbotku01  19971   11     702   2044   273   523   109  23  62   242.0   22.0   11.0  133   571.0   11.0   17.0  21.0  12.0   37.0
16     abbotky01  7974    4      57    31     2     3     1    0   0    2.0     0.0    0.0   1     19.0    0.0    0.0   6.0   0.0    0.0
17     abbotod01  1910    1      22    70     2     13    2    1   0    6.0     3.0    0.0   6     20.0    0.0    0.0   6.0   0.0    0.0
18     abbotpa01  23977   13     162   20     2     5     1    0   0    2.0     0.0    0.0   0     6.0     0.0    0.0   5.0   0.0    0.0
19     aberal01   15635   10     168   100    5     14    0    0   0    6.0     0.0    0.0   8     41.0    0.0    0.0   8.0   1.0    2.0
20     abercda01  1871    1      1     4      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0
21     abercre01  6021    3      180   386    65    86    20   2   9    34.0    18.0   8.0   21    123.0   2.0    7.0   5.0   2.0    3.0
22     abernbi01  1952    1      1     1      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0
23     abernbr01  10014   6      232   868    97    212   36   5   8    79.0    21.0   7.0   60    93.0    1.0    7.0   16.0  4.0    15.0
24     abernte01  5829    3      7     5      0     1     0    0   0    0.0     0.0    0.0   1     3.0     0.0    0.0   0.0   0.0    0.0
25     abernte02  33409   21     681   181    12    25    3    0   0    9.0     0.0    0.0   6     74.0    0.0    2.0   15.0  0.0    4.0
26     abernwo01  3893    2      16    8      0     0     0    0   0    0.0     0.0    0.0   0     4.0     0.0    0.0   0.0   0.0    0.0
27     aberscl01  5844    3      63    179    25    45    7    3   5    26.0    0.0    0.0   25    44.0    0.0    0.0   0.0   0.0    6.0
28     ablesha01  5725    3      14    26     0     0     0    0   0    0.0     1.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0
29     abnersh01  13928   8      392   840    89    191   39   4   11   71.0    6.0    8.0   43    153.0   10.0   7.0   5.0   7.0    14.0
...          ...    ...  ..      ...   ...    ..    ...   ..  ..   ..    ...    ...    ...   ..      ...    ...   ...   ...   ...     ...
18885  zimmejo02  16100   8      200   324    18    55    6    0   1    15.0    0.0    0.0   10    99.0    0.0    0.0   44.0  2.0    2.0
18886  zimmero01  1945    1      27    98     14    27    1    0   5    15.0    1.0    0.0   5     16.0    0.0    3.0   0.0   0.0    2.0
18887  zimmery01  24126   12     1408  5416   793   1505  338  20  215  829.0   41.0   15.0  539   1087.0  41.0   25.0  1.0   58.0   173.0
18888  zinkch01   2008    1      1     0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0
18889  zinkwa01   1921    1      2     1      0     0     0    0   0    0.0     0.0    0.0   0     1.0     0.0    0.0   0.0   0.0    0.0
18890  zinnfr01   1888    1      2     7      0     0     0    0   0    0.0     0.0    0.0   1     0.0     0.0    0.0   0.0   0.0    0.0
18891  zinngu01   9565    5      314   1103   136   297   51   23  15   139.0   28.0   0.0   109   77.0    0.0    6.0   29.0  0.0    0.0
18892  zinnji01   9611    5      76    120    17    34    6    2   2    15.0    2.0    1.0   7     18.0    0.0    1.0   3.0   0.0    0.0
18893  zinsebi01  1944    1      2     0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0
18894  zinteal01  4006    2      67    78     7     13    4    0   3    9.0     0.0    0.0   5     34.0    0.0    0.0   0.0   1.0    0.0
18895  zipfebu01  3923    2      118   354    38    78    11   6   10   39.0    2.0    3.0   32    92.0    1.0    1.0   4.0   2.0    4.0
18896  ziskri01   25701   13     1453  5144   681   1477  245  26  207  792.0   8.0    15.0  533   910.0   52.0   12.0  7.0   41.0   138.0
18897  zitoba01   30106   15     434   344    12    35    0    0   0    11.0    0.0    0.0   18    99.0    0.0    0.0   56.0  0.0    4.0
18898  zitzmbi01  13473   8      406   1004   197   268   38   11  3    89.0    42.0   11.0  83    85.0    0.0    16.0  39.0  0.0    0.0
18899  zmiched01  3821    2      13    17     0     1     0    0   0    1.0     0.0    0.0   0     10.0    0.0    0.0   0.0   0.0    0.0
18900  zobribe01  24136   13     1337  4840   735   1287  296  38  145  643.0   111.0  43.0  700   839.0   32.0   26.0  23.0  55.0   97.0
18901  zoccope01  2003    1      20    37     0     4     1    0   0    3.0     0.0    0.0   2     13.0    0.0    0.0   0.0   0.0    1.0
18902  zoldasa01  19480   11     251   286    16    50    6    0   0    11.0    1.0    0.0   10    52.0    0.0    1.0   9.0   0.0    4.0
18903  zoskyed01  9977    5      44    50     4     8     1    2   0    3.0     0.0    0.0   1     13.0    0.0    0.0   1.0   1.0    1.0
18904  zuberbi01  23307   13     224   229    10    31    4    5   0    11.0    0.0    0.0   10    66.0    0.0    0.0   20.0  0.0    8.0
18905  zuberjo01  3994    2      68    136    13    34    7    1   3    16.0    1.0    0.0   12    20.0    1.0    1.0   1.0   1.0    4.0
18906  zuletju01  4001    2      79    174    24    43    11   0   9    36.0    0.0    2.0   10    51.0    1.0    6.0   0.0   1.0    5.0
18907  zumayjo01  10040   5      171   0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0
18908  zuninmi01  8058    4      350   1125   117   219   43   2   50   133.0   1.0    4.0   75    404.0   1.0    31.0  8.0   8.0    23.0
18909  zupcibo01  9964    6      319   795    99    199   47   4   7    80.0    7.0    5.0   57    137.0   3.0    6.0   20.0  8.0    15.0
18910  zupofr01   5876    3      16    18     3     3     1    0   0    0.0     0.0    0.0   2     6.0     0.0    0.0   0.0   0.0    0.0
18911  zuvelpa01  17875   9      209   491    41    109   17   2   2    20.0    2.0    0.0   34    50.0    1.0    2.0   18.0  0.0    8.0
18912  zuverge01  19551   12     266   142    5     21    2    1   0    7.0     0.0    1.0   9     39.0    0.0    0.0   16.0  0.0    3.0
18913  zwilldu01  7655    4      366   1280   167   364   76   15  30   202.0   46.0   0.0   128   139.0   0.0    4.0   31.0  0.0    0.0
18914  zychto01   4031    2      25    0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0

[18915 rows x 20 columns]

In [77]:
#####
# Creating a new column called 'xb' which is total extra base hits is the sum of dubles (2B) & Triples (3B)
# To reduce autocorrelation in regression model

In [78]:
battingdata['XB'] = battingdata['2B'] + battingdata['3B']

In [79]:
battingdata.head(50)

     playerID  yearID  stint     G     AB     R     H   2B  3B   HR     RBI     SB     CS    BB      SO    IBB   HBP    SH     SF   GIDP   XB
0   aardsda01  18084   9      331   4      0     0     0    0   0    0.0     0.0    0.0    0     2.0     0.0    0.0   1.0   0.0    0.0    0
1   aaronha01  45195   23     3298  12364  2174  3771  624  98  755  2297.0  240.0  73.0   1402  1383.0  293.0  32.0  21.0  121.0  328.0  722
2   aaronto01  13768   7      437   944    102   216   42   6   13   94.0    9.0    8.0    86    145.0   3.0    0.0   9.0   6.0    36.0   48
3   aasedo01   25786   13     448   5      0     0     0    0   0    0.0     0.0    0.0    0     3.0     0.0    0.0   0.0   0.0    0.0    0
4   abadan01   6010    3      15    21     1     2     0    0   0    0.0     0.0    1.0    4     5.0     0.0    0.0   0.0   0.0    1.0    0
5   abadfe01   16107   9      315   9      0     1     0    0   0    0.0     0.0    0.0    0     5.0     0.0    0.0   0.0   0.0    1.0    0
6   abadijo01  3750    3      12    49     4     11    0    0   0    5.0     1.0    0.0    0     3.0     0.0    0.0   0.0   0.0    0.0    0
7   abbated01  19051   11     855   3044   355   772   99   43  11   324.0   142.0  0.0    289   16.0    0.0    33.0  93.0  0.0    0.0    142
8   abbeybe01  11365   7      79    225    21    38    3    3   0    17.0    3.0    0.0    21    54.0    0.0    0.0   4.0   0.0    0.0    6
9   abbeych01  9475    5      451   1751   307   492   67   46  19   280.0   93.0   0.0    167   105.0   0.0    23.0  18.0  0.0    0.0    113
10  abbotda01  1890    1      3     7      0     1     0    1   0    1.0     1.0    0.0    0     0.0     0.0    0.0   0.0   0.0    0.0    1
11  abbotfr01  5712    3      160   513    48    107   21   6   1    49.0    14.0   0.0    19    0.0     0.0    8.0   20.0  0.0    0.0    27
12  abbotgl01  23743   13     248   0      0     0     0    0   0    0.0     0.0    0.0    0     0.0     0.0    0.0   0.0   0.0    0.0    0
13  abbotje01  9995    5      233   596    82    157   33   2   18   83.0    6.0    5.0    38    91.0    2.0    3.0   5.0   7.0    12.0   35
14  abbotji01  21932   12     263   21     0     2     0    0   0    3.0     0.0    0.0    0     10.0    0.0    0.0   3.0   0.0    1.0    0
15  abbotku01  19971   11     702   2044   273   523   109  23  62   242.0   22.0   11.0   133   571.0   11.0   17.0  21.0  12.0   37.0   132
16  abbotky01  7974    4      57    31     2     3     1    0   0    2.0     0.0    0.0    1     19.0    0.0    0.0   6.0   0.0    0.0    1
17  abbotod01  1910    1      22    70     2     13    2    1   0    6.0     3.0    0.0    6     20.0    0.0    0.0   6.0   0.0    0.0    3
18  abbotpa01  23977   13     162   20     2     5     1    0   0    2.0     0.0    0.0    0     6.0     0.0    0.0   5.0   0.0    0.0    1
19  aberal01   15635   10     168   100    5     14    0    0   0    6.0     0.0    0.0    8     41.0    0.0    0.0   8.0   1.0    2.0    0
20  abercda01  1871    1      1     4      0     0     0    0   0    0.0     0.0    0.0    0     0.0     0.0    0.0   0.0   0.0    0.0    0
21  abercre01  6021    3      180   386    65    86    20   2   9    34.0    18.0   8.0    21    123.0   2.0    7.0   5.0   2.0    3.0    22
22  abernbi01  1952    1      1     1      0     0     0    0   0    0.0     0.0    0.0    0     0.0     0.0    0.0   0.0   0.0    0.0    0
23  abernbr01  10014   6      232   868    97    212   36   5   8    79.0    21.0   7.0    60    93.0    1.0    7.0   16.0  4.0    15.0   41
24  abernte01  5829    3      7     5      0     1     0    0   0    0.0     0.0    0.0    1     3.0     0.0    0.0   0.0   0.0    0.0    0
25  abernte02  33409   21     681   181    12    25    3    0   0    9.0     0.0    0.0    6     74.0    0.0    2.0   15.0  0.0    4.0    3
26  abernwo01  3893    2      16    8      0     0     0    0   0    0.0     0.0    0.0    0     4.0     0.0    0.0   0.0   0.0    0.0    0
27  aberscl01  5844    3      63    179    25    45    7    3   5    26.0    0.0    0.0    25    44.0    0.0    0.0   0.0   0.0    6.0    10
28  ablesha01  5725    3      14    26     0     0     0    0   0    0.0     1.0    0.0    0     0.0     0.0    0.0   0.0   0.0    0.0    0
29  abnersh01  13928   8      392   840    89    191   39   4   11   71.0    6.0    8.0    43    153.0   10.0   7.0   5.0   7.0    14.0   43
30  abramca01  19526   12     567   1611   257   433   64   19  32   138.0   12.0   18.0   304   290.0   2.0    7.0   16.0  4.0    22.0   83
31  abramge01  1923    1      3     1      0     1     0    0   0    0.0     0.0    0.0    0     0.0     0.0    0.0   0.0   0.0    0.0    0
32  abregjo01  1985    1      6     9      0     0     0    0   0    1.0     0.0    0.0    0     2.0     0.0    0.0   0.0   0.0    0.0    0
33  abreubo01  40100   22     2425  8480   1453  2470  574  59  288  1363.0  400.0  128.0  1476  1840.0  115.0  33.0  7.0   85.0   165.0  633
34  abreujo01  1942    1      9     28     4     6     1    0   1    3.0     0.0    0.0    4     4.0     0.0    0.0   0.0   0.0    1.0    1
35  abreujo02  6045    3      458   1793   235   537   101  6   91   308.0   3.0    3.0    137   396.0   33.0   41.0  0.0   14.0   51.0   107
36  abreuju01  2011    1      7     0      0     0     0    0   0    0.0     0.0    0.0    0     0.0     0.0    0.0   0.0   0.0    0.0    0
37  abreuto01  12065   6      224   579    61    147   39   6   6    60.0    2.0    4.0    22    116.0   2.0    5.0   1.0   8.0    20.0   45
38  abreuwi01  8031    5      38    2      0     0     0    0   0    0.0     0.0    0.0    0     1.0     0.0    0.0   0.0   0.0    0.0    0
39  abstebi01  5725    3      170   619    54    150   22   10  1    76.0    21.0   0.0    29    0.0     0.0    4.0   29.0  0.0    0.0    32
40  accarje01  20086   12     262   7      0     1     0    0   0    0.0     0.0    0.0    0     1.0     0.0    0.0   0.0   0.0    0.0    0
41  aceveal01  14077   7      204   2      0     0     0    0   0    0.0     0.0    0.0    0     1.0     0.0    0.0   0.0   0.0    0.0    0
42  acevejo01  10015   5      104   101    2     8     2    0   0    4.0     0.0    0.0    5     61.0    0.0    1.0   12.0  1.0    2.0    2
43  aceveju01  19999   12     367   65     4     6     2    0   0    0.0     0.0    0.0    3     33.0    0.0    0.0   6.0   0.0    2.0    2
44  achteaj01  6045    3      45    0      0     0     0    0   0    0.0     0.0    0.0    0     0.0     0.0    0.0   0.0   0.0    0.0    0
45  ackerji01  23850   14     467   54     2     9     1    0   0    1.0     0.0    0.0    2     32.0    0.0    0.0   0.0   0.0    1.0    1
46  ackerto01  7830    4      153   77     10    5     0    0   0    2.0     0.0    0.0    12    46.0    0.0    1.0   6.0   0.0    1.0    0
47  ackledu01  14096   8      635   2125   261   512   94   18  46   216.0   31.0   12.0   194   419.0   10.0   5.0   11.0  12.0   25.0   112
48  acklefr01  3927    2      5     6      0     2     1    0   0    1.0     0.0    0.0    1     4.0     0.0    0.0   0.0   0.0    0.0    1
49  acostcy01  7894    4      107   7      0     0     0    0   0    0.0     0.0    0.0    0     6.0     0.0    0.0   0.0   0.0    0.0    0

In [80]:
battingdata

        playerID  yearID  stint     G     AB     R     H   2B  3B   HR     RBI     SB    CS    BB      SO    IBB   HBP    SH     SF   GIDP   XB
0      aardsda01  18084   9      331   4      0     0     0    0   0    0.0     0.0    0.0   0     2.0     0.0    0.0   1.0   0.0    0.0    0
1      aaronha01  45195   23     3298  12364  2174  3771  624  98  755  2297.0  240.0  73.0  1402  1383.0  293.0  32.0  21.0  121.0  328.0  722
2      aaronto01  13768   7      437   944    102   216   42   6   13   94.0    9.0    8.0   86    145.0   3.0    0.0   9.0   6.0    36.0   48
3      aasedo01   25786   13     448   5      0     0     0    0   0    0.0     0.0    0.0   0     3.0     0.0    0.0   0.0   0.0    0.0    0
4      abadan01   6010    3      15    21     1     2     0    0   0    0.0     0.0    1.0   4     5.0     0.0    0.0   0.0   0.0    1.0    0
5      abadfe01   16107   9      315   9      0     1     0    0   0    0.0     0.0    0.0   0     5.0     0.0    0.0   0.0   0.0    1.0    0
6      abadijo01  3750    3      12    49     4     11    0    0   0    5.0     1.0    0.0   0     3.0     0.0    0.0   0.0   0.0    0.0    0
7      abbated01  19051   11     855   3044   355   772   99   43  11   324.0   142.0  0.0   289   16.0    0.0    33.0  93.0  0.0    0.0    142
8      abbeybe01  11365   7      79    225    21    38    3    3   0    17.0    3.0    0.0   21    54.0    0.0    0.0   4.0   0.0    0.0    6
9      abbeych01  9475    5      451   1751   307   492   67   46  19   280.0   93.0   0.0   167   105.0   0.0    23.0  18.0  0.0    0.0    113
10     abbotda01  1890    1      3     7      0     1     0    1   0    1.0     1.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    1
11     abbotfr01  5712    3      160   513    48    107   21   6   1    49.0    14.0   0.0   19    0.0     0.0    8.0   20.0  0.0    0.0    27
12     abbotgl01  23743   13     248   0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    0
13     abbotje01  9995    5      233   596    82    157   33   2   18   83.0    6.0    5.0   38    91.0    2.0    3.0   5.0   7.0    12.0   35
14     abbotji01  21932   12     263   21     0     2     0    0   0    3.0     0.0    0.0   0     10.0    0.0    0.0   3.0   0.0    1.0    0
15     abbotku01  19971   11     702   2044   273   523   109  23  62   242.0   22.0   11.0  133   571.0   11.0   17.0  21.0  12.0   37.0   132
16     abbotky01  7974    4      57    31     2     3     1    0   0    2.0     0.0    0.0   1     19.0    0.0    0.0   6.0   0.0    0.0    1
17     abbotod01  1910    1      22    70     2     13    2    1   0    6.0     3.0    0.0   6     20.0    0.0    0.0   6.0   0.0    0.0    3
18     abbotpa01  23977   13     162   20     2     5     1    0   0    2.0     0.0    0.0   0     6.0     0.0    0.0   5.0   0.0    0.0    1
19     aberal01   15635   10     168   100    5     14    0    0   0    6.0     0.0    0.0   8     41.0    0.0    0.0   8.0   1.0    2.0    0
20     abercda01  1871    1      1     4      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    0
21     abercre01  6021    3      180   386    65    86    20   2   9    34.0    18.0   8.0   21    123.0   2.0    7.0   5.0   2.0    3.0    22
22     abernbi01  1952    1      1     1      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    0
23     abernbr01  10014   6      232   868    97    212   36   5   8    79.0    21.0   7.0   60    93.0    1.0    7.0   16.0  4.0    15.0   41
24     abernte01  5829    3      7     5      0     1     0    0   0    0.0     0.0    0.0   1     3.0     0.0    0.0   0.0   0.0    0.0    0
25     abernte02  33409   21     681   181    12    25    3    0   0    9.0     0.0    0.0   6     74.0    0.0    2.0   15.0  0.0    4.0    3
26     abernwo01  3893    2      16    8      0     0     0    0   0    0.0     0.0    0.0   0     4.0     0.0    0.0   0.0   0.0    0.0    0
27     aberscl01  5844    3      63    179    25    45    7    3   5    26.0    0.0    0.0   25    44.0    0.0    0.0   0.0   0.0    6.0    10
28     ablesha01  5725    3      14    26     0     0     0    0   0    0.0     1.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    0
29     abnersh01  13928   8      392   840    89    191   39   4   11   71.0    6.0    8.0   43    153.0   10.0   7.0   5.0   7.0    14.0   43
...          ...    ...  ..      ...   ...    ..    ...   ..  ..   ..    ...    ...    ...   ..      ...    ...   ...   ...   ...     ...   ..
18885  zimmejo02  16100   8      200   324    18    55    6    0   1    15.0    0.0    0.0   10    99.0    0.0    0.0   44.0  2.0    2.0    6
18886  zimmero01  1945    1      27    98     14    27    1    0   5    15.0    1.0    0.0   5     16.0    0.0    3.0   0.0   0.0    2.0    1
18887  zimmery01  24126   12     1408  5416   793   1505  338  20  215  829.0   41.0   15.0  539   1087.0  41.0   25.0  1.0   58.0   173.0  358
18888  zinkch01   2008    1      1     0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    0
18889  zinkwa01   1921    1      2     1      0     0     0    0   0    0.0     0.0    0.0   0     1.0     0.0    0.0   0.0   0.0    0.0    0
18890  zinnfr01   1888    1      2     7      0     0     0    0   0    0.0     0.0    0.0   1     0.0     0.0    0.0   0.0   0.0    0.0    0
18891  zinngu01   9565    5      314   1103   136   297   51   23  15   139.0   28.0   0.0   109   77.0    0.0    6.0   29.0  0.0    0.0    74
18892  zinnji01   9611    5      76    120    17    34    6    2   2    15.0    2.0    1.0   7     18.0    0.0    1.0   3.0   0.0    0.0    8
18893  zinsebi01  1944    1      2     0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    0
18894  zinteal01  4006    2      67    78     7     13    4    0   3    9.0     0.0    0.0   5     34.0    0.0    0.0   0.0   1.0    0.0    4
18895  zipfebu01  3923    2      118   354    38    78    11   6   10   39.0    2.0    3.0   32    92.0    1.0    1.0   4.0   2.0    4.0    17
18896  ziskri01   25701   13     1453  5144   681   1477  245  26  207  792.0   8.0    15.0  533   910.0   52.0   12.0  7.0   41.0   138.0  271
18897  zitoba01   30106   15     434   344    12    35    0    0   0    11.0    0.0    0.0   18    99.0    0.0    0.0   56.0  0.0    4.0    0
18898  zitzmbi01  13473   8      406   1004   197   268   38   11  3    89.0    42.0   11.0  83    85.0    0.0    16.0  39.0  0.0    0.0    49
18899  zmiched01  3821    2      13    17     0     1     0    0   0    1.0     0.0    0.0   0     10.0    0.0    0.0   0.0   0.0    0.0    0
18900  zobribe01  24136   13     1337  4840   735   1287  296  38  145  643.0   111.0  43.0  700   839.0   32.0   26.0  23.0  55.0   97.0   334
18901  zoccope01  2003    1      20    37     0     4     1    0   0    3.0     0.0    0.0   2     13.0    0.0    0.0   0.0   0.0    1.0    1
18902  zoldasa01  19480   11     251   286    16    50    6    0   0    11.0    1.0    0.0   10    52.0    0.0    1.0   9.0   0.0    4.0    6
18903  zoskyed01  9977    5      44    50     4     8     1    2   0    3.0     0.0    0.0   1     13.0    0.0    0.0   1.0   1.0    1.0    3
18904  zuberbi01  23307   13     224   229    10    31    4    5   0    11.0    0.0    0.0   10    66.0    0.0    0.0   20.0  0.0    8.0    9
18905  zuberjo01  3994    2      68    136    13    34    7    1   3    16.0    1.0    0.0   12    20.0    1.0    1.0   1.0   1.0    4.0    8
18906  zuletju01  4001    2      79    174    24    43    11   0   9    36.0    0.0    2.0   10    51.0    1.0    6.0   0.0   1.0    5.0    11
18907  zumayjo01  10040   5      171   0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    0
18908  zuninmi01  8058    4      350   1125   117   219   43   2   50   133.0   1.0    4.0   75    404.0   1.0    31.0  8.0   8.0    23.0   45
18909  zupcibo01  9964    6      319   795    99    199   47   4   7    80.0    7.0    5.0   57    137.0   3.0    6.0   20.0  8.0    15.0   51
18910  zupofr01   5876    3      16    18     3     3     1    0   0    0.0     0.0    0.0   2     6.0     0.0    0.0   0.0   0.0    0.0    1
18911  zuvelpa01  17875   9      209   491    41    109   17   2   2    20.0    2.0    0.0   34    50.0    1.0    2.0   18.0  0.0    8.0    19
18912  zuverge01  19551   12     266   142    5     21    2    1   0    7.0     0.0    1.0   9     39.0    0.0    0.0   16.0  0.0    3.0    3
18913  zwilldu01  7655    4      366   1280   167   364   76   15  30   202.0   46.0   0.0   128   139.0   0.0    4.0   31.0  0.0    0.0    91
18914  zychto01   4031    2      25    0      0     0     0    0   0    0.0     0.0    0.0   0     0.0     0.0    0.0   0.0   0.0    0.0    0

[18915 rows x 21 columns]

In [81]:
battingdata.dtypes

playerID    object
yearID      int64
stint       int64
G           int64
AB          int64
R           int64
H           int64
2B          int64
3B          int64
HR          int64
RBI         float64
SB          float64
CS          float64
BB          int64
SO          float64
IBB         float64
HBP         float64
SH          float64
SF          float64
GIDP        float64
XB          int64
dtype: object

In [82]:
mlb = battingdata.merge(hallOfFame, left_on='playerID', right_on='playerID')
mlb.head(20)

     playerID  yearID  stint     G     AB     R     H   2B  3B   HR     RBI     SB    CS    BB      SO    IBB   HBP     SH     SF   GIDP   XB  yearid          votedBy  ballots  needed  votes inducted category needed_note
0   aaronha01  45195   23     3298  12364  2174  3771  624  98  755  2297.0  240.0  73.0  1402  1383.0  293.0  32.0  21.0   121.0  328.0  722  1982    BBWAA            415.0    312.0   406.0  Y        Player   NaN
1   abbotji01  21932   12     263   21     0     2     0    0   0    3.0     0.0    0.0   0     10.0    0.0    0.0   3.0    0.0    1.0    0    2005    BBWAA            516.0    387.0   13.0   N        Player   NaN
2   adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1937    BBWAA            201.0    151.0   8.0    N        Player   NaN
3   adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1938    BBWAA            262.0    197.0   11.0   N        Player   NaN
4   adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1939    BBWAA            274.0    206.0   11.0   N        Player   NaN
5   adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1942    BBWAA            233.0    175.0   11.0   N        Player   NaN
6   adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1945    BBWAA            247.0    186.0   7.0    N        Player   NaN
7   adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1946    Nominating Vote  202.0   NaN      6.0    N        Player   Top 20
8   adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1947    BBWAA            161.0    121.0   22.0   N        Player   NaN
9   adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1948    BBWAA            121.0    91.0    4.0    N        Player   NaN
10  adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1949    BBWAA            153.0    115.0   5.0    N        Player   NaN
11  adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1950    BBWAA            168.0    126.0   6.0    N        Player   NaN
12  adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1951    BBWAA            226.0    170.0   12.0   N        Player   NaN
13  adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1952    BBWAA            234.0    176.0   9.0    N        Player   NaN
14  adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1953    BBWAA            264.0    198.0   17.0   N        Player   NaN
15  adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1954    BBWAA            252.0    189.0   13.0   N        Player   NaN
16  adamsba01  36411   19     482   1019   79    216   31   15  3    75.0    1.0    1.0   53    177.0   0.0    1.0   35.0   0.0    0.0    46   1955    BBWAA            251.0    189.0   24.0   N        Player   NaN
17  adamsbo03  29290   16     1281  4019   591   1082  188  49  37   303.0   67.0   30.0  414   447.0   1.0    17.0  78.0   5.0    62.0   237  1966    BBWAA            302.0    227.0   1.0    N        Player   NaN
18  adamssp01  26997   15     1424  5557   844   1588  249  48  9    394.0   154.0  50.0  453   223.0   0.0    28.0  136.0  0.0    14.0   297  1958    BBWAA            266.0    200.0   1.0    N        Player   NaN
19  adamssp01  26997   15     1424  5557   844   1588  249  48  9    394.0   154.0  50.0  453   223.0   0.0    28.0  136.0  0.0    14.0   297  1960    BBWAA            269.0    202.0   1.0    N        Player   NaN

In [98]:
cols_obj = [cols for cols in mlb.columns if str(mlb[cols].dtype) =="object"]

cols_obj

mlb[cols_obj].describe().T

            count unique        top  freq
playerID     4084  1193   roushed01  20
votedBy      4084  9      BBWAA      3717
inducted     4084  2      N          3833
category     4084  4      Player     4004
needed_note  157   2      1st        81

In [147]:
playerGroup = mlb.groupby(['playerID'],as_index=False).mean()
playerGroup

       playerID   yearID  stint       G       AB       R       H     2B     3B     HR     RBI     SB     CS      BB      SO    IBB    HBP     SH     SF   GIDP     XB       yearid     ballots      needed       votes
0     aaronha01  45195.0  23.0   3298.0  12364.0  2174.0  3771.0  624.0  98.0   755.0  2297.0  240.0  73.0   1402.0  1383.0  293.0  32.0   21.0   121.0  328.0  722.0  1982.000000  415.000000  312.000000  406.000000
1     abbotji01  21932.0  12.0   263.0   21.0     0.0     2.0     0.0    0.0    0.0    3.0     0.0    0.0    0.0     10.0    0.0    0.0    3.0    0.0    1.0    0.0    2005.000000  516.000000  387.000000  13.000000
2     adamsba01  36411.0  19.0   482.0   1019.0   79.0    216.0   31.0   15.0   3.0    75.0    1.0    1.0    53.0    177.0   0.0    1.0    35.0   0.0    0.0    46.0   1947.066667  216.600000  163.571429  11.066667
3     adamsbo03  29290.0  16.0   1281.0  4019.0   591.0   1082.0  188.0  49.0   37.0   303.0   67.0   30.0   414.0   447.0   1.0    17.0   78.0   5.0    62.0   237.0  1966.000000  302.000000  227.000000  1.000000
4     adamssp01  26997.0  15.0   1424.0  5557.0   844.0   1588.0  249.0  48.0   9.0    394.0   154.0  50.0   453.0   223.0   0.0    28.0   136.0  0.0    14.0   297.0  1959.000000  267.500000  201.000000  1.000000
5     ageeto01   25583.0  14.0   1129.0  3912.0   558.0   999.0   170.0  27.0   130.0  433.0   167.0  81.0   342.0   918.0   26.0   34.0   21.0   15.0   99.0   197.0  1979.000000  432.000000  324.000000  0.000000
6     aguilri01  37863.0  22.0   737.0   139.0    12.0    28.0    3.0    0.0    3.0    11.0    0.0    0.0    6.0     37.0    0.0    0.0    16.0   0.0    1.0    3.0    2006.000000  520.000000  390.000000  3.000000
7     akerja01   27574.0  17.0   496.0   92.0     3.0     7.0     2.0    0.0    0.0    4.0     0.0    0.0    1.0     51.0    0.0    1.0    10.0   0.0    1.0    2.0    1980.000000  385.000000  289.000000  0.000000
8     alexado01  45552.0  27.0   562.0   265.0    19.0    44.0    8.0    0.0    0.0    17.0    0.0    0.0    9.0     77.0    0.0    1.0    23.0   2.0    7.0    8.0    1995.000000  460.000000  345.000000  0.000000
9     alexape01  40336.0  22.0   703.0   1810.0   154.0   378.0   60.0   13.0   11.0   163.0   3.0    5.0    77.0    276.0   0.0    2.0    88.0   0.0    0.0    73.0   1937.000000  229.666667  172.666667  130.666667
10    allenbe01  25583.0  14.0   1139.0  3404.0   357.0   815.0   140.0  21.0   73.0   351.0   13.0   16.0   370.0   424.0   52.0   8.0    24.0   17.0   60.0   161.0  1979.000000  432.000000  324.000000  0.000000
11    allendi01  29550.0  15.0   1749.0  6332.0   1099.0  1848.0  320.0  79.0   351.0  1119.0  133.0  52.0   894.0   1556.0  138.0  16.0   19.0   53.0   164.0  399.0  1990.428571  434.285714  326.000000  56.214286
12    allenjo02  29078.0  17.0   365.0   716.0    82.0    124.0   12.0   3.0    4.0    64.0    1.0    0.0    33.0    155.0   0.0    0.0    36.0   0.0    8.0    15.0   1955.000000  251.000000  189.000000  1.000000
13    alleyge01  21648.0  11.0   1195.0  3927.0   442.0   999.0   140.0  44.0   55.0   342.0   63.0   30.0   300.0   622.0   62.0   27.0   56.0   22.0   95.0   184.0  1979.000000  432.000000  324.000000  0.000000
14    allisdo01  22503.0  14.0   318.0   1407.0   236.0   381.0   43.0   10.0   2.0    140.0   5.0    2.0    22.0    40.0    0.0    0.0    0.0    0.0    0.0    53.0   1936.000000  78.000000   59.000000   1.000000
15    alomaro01  37939.0  21.0   2379.0  9073.0   1508.0  2724.0  504.0  80.0   210.0  1134.0  474.0  114.0  1032.0  1140.0  62.0   50.0   148.0  97.0   206.0  584.0  2010.500000  560.000000  420.500000  460.000000
16    alomasa02  43958.0  24.0   1377.0  4530.0   520.0   1236.0  249.0  10.0   112.0  588.0   25.0   24.0   212.0   499.0   15.0   41.0   48.0   34.0   132.0  259.0  2013.000000  569.000000  427.000000  16.000000
17    aloufe01   37366.0  21.0   2082.0  7339.0   985.0   2101.0  359.0  49.0   206.0  852.0   107.0  67.0   423.0   706.0   67.0   57.0   33.0   56.0   135.0  408.0  1980.000000  385.000000  289.000000  3.000000
18    alouje01   31527.0  17.0   1380.0  4345.0   448.0   1216.0  170.0  26.0   32.0   377.0   31.0   46.0   138.0   267.0   32.0   30.0   44.0   20.0   143.0  196.0  1985.000000  395.000000  297.000000  1.000000
19    alouma01   33450.0  19.0   1667.0  5789.0   780.0   1777.0  236.0  50.0   31.0   427.0   156.0  80.0   311.0   377.0   38.0   36.0   55.0   29.0   101.0  286.0  1980.000000  385.000000  289.000000  5.000000
20    aloumo01   35981.0  19.0   1942.0  7037.0   1109.0  2134.0  421.0  39.0   332.0  1287.0  106.0  37.0   737.0   894.0   91.0   48.0   9.0    82.0   195.0  460.0  2014.000000  571.000000  429.000000  6.000000
21    alstowa01  1936.0   1.0    1.0     1.0      0.0     0.0     0.0    0.0    0.0    0.0     0.0    0.0    0.0     1.0     0.0    0.0    0.0    0.0    0.0    0.0    1983.000000 NaN         NaN         NaN
22    altroni01  40162.0  23.0   230.0   550.0    52.0    97.0    9.0    1.0    2.0    27.0    5.0    1.0    29.0    0.0     0.0    11.0   15.0   0.0    0.0    10.0   1949.375000  247.625000  186.000000  7.250000
23    anderbr01  31913.0  17.0   1834.0  6499.0   1062.0  1661.0  338.0  67.0   210.0  761.0   315.0  100.0  960.0   1190.0  59.0   154.0  74.0   50.0   65.0   405.0  2008.000000  543.000000  408.000000  0.000000
24    anderga01  34034.0  17.0   2228.0  8640.0   1084.0  2529.0  522.0  36.0   287.0  1365.0  80.0   47.0   429.0   1224.0  104.0  8.0    13.0   87.0   197.0  558.0  2016.000000  440.000000  330.000000  1.000000
25    andersp01  1959.0   1.0    152.0   477.0    42.0    104.0   9.0    3.0    0.0    34.0    6.0    9.0    42.0    53.0    1.0    1.0    5.0    2.0    15.0   12.0   2000.000000 NaN         NaN         NaN
26    ansonca01  50868.0  27.0   2523.0  10277.0  1996.0  3418.0  581.0  142.0  97.0   2076.0  276.0  16.0   983.0   302.0   0.0    32.0   27.0   0.0    0.0    723.0  1937.500000  78.000000   59.000000   39.000000
27    aparilu01  35361.0  18.0   2601.0  10230.0  1335.0  2677.0  394.0  92.0   83.0   791.0   506.0  136.0  736.0   742.0   22.0   27.0   161.0  76.0   184.0  486.0  1981.500000  401.666667  301.666667  193.166667
28    appieke01  35946.0  20.0   414.0   83.0     4.0     8.0     0.0    0.0    0.0    4.0     0.0    0.0    1.0     39.0    0.0    1.0    5.0    0.0    0.0    0.0    2010.000000  539.000000  405.000000  1.000000
29    applilu01  38796.0  20.0   2422.0  8856.0   1319.0  2749.0  440.0  102.0  45.0   1116.0  179.0  108.0  1302.0  528.0   0.0    11.0   74.0   0.0    129.0  542.0  1959.000000  225.625000  172.142857  68.375000
...         ...      ...   ...      ...     ...      ...     ...    ...    ...   ...      ...    ...    ...     ...    ...   ...     ...    ...   ...      ...    ...          ...         ...         ...        ...
1163  winnra01   30067.0  17.0   1717.0  6186.0   863.0   1759.0  367.0  59.0   110.0  662.0   215.0  84.0   526.0   1010.0  23.0   53.0   58.0   55.0   98.0   426.0  2016.000000  440.000000  330.000000  0.000000
1164  wiseri01   35522.0  18.0   511.0   668.0    60.0    130.0   21.0   5.0    15.0   66.0    0.0    0.0    27.0    240.0   0.0    3.0    40.0   3.0    7.0    26.0   1988.000000  427.000000  321.000000  0.000000
1165  wittbo01   37881.0  22.0   438.0   64.0     2.0     9.0     3.0    0.0    1.0    5.0     0.0    0.0    2.0     25.0    0.0    0.0    6.0    1.0    0.0    3.0    2007.000000  545.000000  409.000000  0.000000
1166  wittmi01   25829.0  14.0   341.0   0.0      0.0     0.0     0.0    0.0    0.0    0.0     0.0    0.0    0.0     0.0     0.0    0.0    0.0    0.0    0.0    0.0    1999.000000  497.000000  373.000000  0.000000
1167  wittwh01   19213.0  10.0   1139.0  4171.0   632.0   1195.0  144.0  62.0   18.0   302.0   78.0   41.0   489.0   309.0   0.0    7.0    104.0  0.0    0.0    206.0  1949.000000  153.000000  115.000000  1.000000
1168  womacto01  32010.0  20.0   1303.0  4963.0   739.0   1353.0  190.0  59.0   36.0   368.0   363.0  74.0   308.0   649.0   9.0    28.0   57.0   33.0   53.0   249.0  2012.000000  573.000000  430.000000  0.000000
1169  woodjo02   26809.0  14.0   696.0   1952.0   266.0   553.0   118.0  31.0   23.0   325.0   23.0   3.0    208.0   189.0   0.0    16.0   96.0   0.0    0.0    149.0  1944.222222  205.333333  154.625000  7.444444
1170  woodwi01   35449.0  19.0   651.0   322.0    11.0    27.0    2.0    0.0    0.0    13.0    1.0    0.0    20.0    189.0   0.0    1.0    38.0   0.0    7.0    2.0    1986.500000  418.333333  314.333333  20.500000
1171  worreto01  21902.0  11.0   617.0   27.0     1.0     2.0     0.0    1.0    0.0    0.0     0.0    0.0    1.0     20.0    0.0    0.0    2.0    0.0    1.0    1.0    2003.000000  496.000000  372.000000  0.000000
1172  wrighge01  22518.0  12.0   591.0   2875.0   665.0   867.0   126.0  61.0   11.0   330.0   41.0   16.0   67.0    119.0   0.0    0.0    0.0    0.0    0.0    187.0  1936.500000  78.000000   59.000000   6.000000
1173  wrighgl01  21220.0  11.0   1119.0  4153.0   584.0   1219.0  203.0  76.0   94.0   723.0   38.0   13.0   209.0   407.0   0.0    5.0    113.0  0.0    9.0    279.0  1954.000000  213.083333  160.083333  3.750000
1174  wrighha01  13118.0  7.0    180.0   816.0    183.0   222.0   24.0   9.0    4.0    111.0   9.0    2.0    36.0    12.0    0.0    0.0    0.0    0.0    0.0    33.0   1953.000000 NaN         NaN         NaN
1175  wyattwh01  32924.0  18.0   366.0   607.0    53.0    133.0   26.0   2.0    7.0    69.0    0.0    0.0    26.0    111.0   0.0    2.0    34.0   0.0    20.0   28.0   1958.000000  266.000000  200.000000  1.000000
1176  wynnea01   44890.0  23.0   796.0   1704.0   136.0   365.0   59.0   5.0    17.0   173.0   1.0    0.0    141.0   330.0   0.0    2.0    52.0   4.0    33.0   64.0   1970.500000  349.000000  261.750000  194.000000
1177  wynnji01   31527.0  17.0   1920.0  6653.0   1105.0  1665.0  285.0  39.0   291.0  964.0   225.0  101.0  1224.0  1427.0  84.0   27.0   32.0   74.0   117.0  324.0  1983.000000  374.000000  281.000000  0.000000
1178  yastrca01  45356.0  23.0   3308.0  11988.0  1816.0  3419.0  646.0  59.0   452.0  1844.0  168.0  116.0  1845.0  1393.0  190.0  40.0   13.0   105.0  323.0  705.0  1989.000000  447.000000  336.000000  423.000000
1179  yeagest01  29685.0  15.0   1269.0  3584.0   357.0   816.0   118.0  16.0   102.0  410.0   14.0   18.0   342.0   726.0   64.0   27.0   33.0   28.0   93.0   134.0  1992.000000  430.000000  323.000000  2.000000
1180  yerkest02  15304.0  9.0    711.0   2521.0   307.0   676.0   124.0  32.0   6.0    254.0   54.0   6.0    207.0   102.0   0.0    16.0   115.0  0.0    0.0    156.0  1945.000000  247.000000  186.000000  1.000000
1181  yorkru01   27191.0  15.0   1603.0  5891.0   876.0   1621.0  291.0  52.0   277.0  1152.0  38.0   26.0   792.0   867.0   0.0    12.0   25.0   0.0    155.0  343.0  1963.000000  180.500000  135.500000  5.500000
1182  youngcy01  43722.0  24.0   918.0   2960.0   325.0   623.0   87.0   35.0   18.0   290.0   29.0   0.0    81.0    150.0   0.0    10.0   50.0   0.0    0.0    122.0  1936.333333  168.333333  126.666667  98.666667
1183  younger01  35991.0  21.0   1730.0  6119.0   996.0   1731.0  327.0  46.0   79.0   543.0   465.0  168.0  660.0   462.0   14.0   89.0   84.0   44.0   135.0  373.0  2012.000000  573.000000  430.000000  1.000000
1184  youngpe01  21319.0  12.0   730.0   2466.0   274.0   645.0   128.0  34.0   32.0   347.0   18.0   0.0    152.0   312.0   0.0    12.0   38.0   0.0    51.0   162.0  1958.000000  266.000000  200.000000  1.000000
1185  youngro01  19215.0  10.0   1211.0  4627.0   812.0   1491.0  236.0  93.0   42.0   592.0   153.0  83.0   550.0   390.0   0.0    37.0   119.0  0.0    0.0    329.0  1948.368421  214.166667  162.812500  27.444444
1186  yountro01  39670.0  20.0   2856.0  11008.0  1632.0  3142.0  583.0  126.0  251.0  1406.0  271.0  105.0  966.0   1350.0  95.0   48.0   104.0  123.0  217.0  709.0  1999.000000  497.000000  373.000000  385.000000
1187  zachato01  46268.0  29.0   546.0   1122.0   79.0    254.0   28.0   12.0   6.0    112.0   0.0    1.0    62.0    261.0   0.0    2.0    46.0   0.0    7.0    40.0   1959.000000  267.500000  201.000000  1.000000
1188  zachrpa01  21782.0  12.0   293.0   318.0    9.0     36.0    0.0    0.0    0.0    6.0     0.0    0.0    14.0    128.0   0.0    0.0    33.0   2.0    11.0   0.0    1991.000000  443.000000  333.000000  0.000000
1189  zahnge01   27702.0  15.0   304.0   43.0     3.0     6.0     0.0    0.0    0.0    1.0     0.0    0.0    0.0     9.0     0.0    0.0    10.0   0.0    1.0    0.0    1991.000000  443.000000  333.000000  0.000000
1190  zeileto01  41934.0  27.0   2158.0  7573.0   986.0   2004.0  397.0  23.0   253.0  1110.0  53.0   51.0   945.0   1279.0  47.0   42.0   8.0    81.0   223.0  420.0  2010.000000  539.000000  405.000000  0.000000
1191  zimmech01  37884.0  21.0   1280.0  4546.0   617.0   1224.0  222.0  76.0   26.0   625.0   151.0  0.0    390.0   323.0   0.0    91.0   49.0   0.0    0.0    298.0  1938.000000  262.000000  197.000000  1.000000
1192  ziskri01   25701.0  13.0   1453.0  5144.0   681.0   1477.0  245.0  26.0   207.0  792.0   8.0    15.0   533.0   910.0   52.0   12.0   7.0    41.0   138.0  271.0  1989.000000  447.000000  336.000000  0.000000

[1193 rows x 25 columns]

In [148]:
# Delete players who have null values for needed or votes
playerGroup.dropna(subset=["needed","votes"],inplace=True)

In [149]:
playerGroup.isnull().sum()

playerID    0
yearID      0
stint       0
G           0
AB          0
R           0
H           0
2B          0
3B          0
HR          0
RBI         0
SB          0
CS          0
BB          0
SO          0
IBB         0
HBP         0
SH          0
SF          0
GIDP        0
XB          0
yearid      0
ballots     0
needed      0
votes       0
dtype: int64

In [150]:
playerGroup.shape

(1168, 25)

In [151]:
playerGroup['inducted'] = np.where(playerGroup['votes'] > playerGroup['needed'], 'Y', 'N')

In [152]:
playerGroup

       playerID   yearID  stint       G       AB       R       H     2B     3B     HR     RBI     SB     CS      BB      SO    IBB    HBP     SH     SF   GIDP     XB       yearid     ballots      needed       votes inducted
0     aaronha01  45195.0  23.0   3298.0  12364.0  2174.0  3771.0  624.0  98.0   755.0  2297.0  240.0  73.0   1402.0  1383.0  293.0  32.0   21.0   121.0  328.0  722.0  1982.000000  415.000000  312.000000  406.000000  Y
1     abbotji01  21932.0  12.0   263.0   21.0     0.0     2.0     0.0    0.0    0.0    3.0     0.0    0.0    0.0     10.0    0.0    0.0    3.0    0.0    1.0    0.0    2005.000000  516.000000  387.000000  13.000000   N
2     adamsba01  36411.0  19.0   482.0   1019.0   79.0    216.0   31.0   15.0   3.0    75.0    1.0    1.0    53.0    177.0   0.0    1.0    35.0   0.0    0.0    46.0   1947.066667  216.600000  163.571429  11.066667   N
3     adamsbo03  29290.0  16.0   1281.0  4019.0   591.0   1082.0  188.0  49.0   37.0   303.0   67.0   30.0   414.0   447.0   1.0    17.0   78.0   5.0    62.0   237.0  1966.000000  302.000000  227.000000  1.000000    N
4     adamssp01  26997.0  15.0   1424.0  5557.0   844.0   1588.0  249.0  48.0   9.0    394.0   154.0  50.0   453.0   223.0   0.0    28.0   136.0  0.0    14.0   297.0  1959.000000  267.500000  201.000000  1.000000    N
5     ageeto01   25583.0  14.0   1129.0  3912.0   558.0   999.0   170.0  27.0   130.0  433.0   167.0  81.0   342.0   918.0   26.0   34.0   21.0   15.0   99.0   197.0  1979.000000  432.000000  324.000000  0.000000    N
6     aguilri01  37863.0  22.0   737.0   139.0    12.0    28.0    3.0    0.0    3.0    11.0    0.0    0.0    6.0     37.0    0.0    0.0    16.0   0.0    1.0    3.0    2006.000000  520.000000  390.000000  3.000000    N
7     akerja01   27574.0  17.0   496.0   92.0     3.0     7.0     2.0    0.0    0.0    4.0     0.0    0.0    1.0     51.0    0.0    1.0    10.0   0.0    1.0    2.0    1980.000000  385.000000  289.000000  0.000000    N
8     alexado01  45552.0  27.0   562.0   265.0    19.0    44.0    8.0    0.0    0.0    17.0    0.0    0.0    9.0     77.0    0.0    1.0    23.0   2.0    7.0    8.0    1995.000000  460.000000  345.000000  0.000000    N
9     alexape01  40336.0  22.0   703.0   1810.0   154.0   378.0   60.0   13.0   11.0   163.0   3.0    5.0    77.0    276.0   0.0    2.0    88.0   0.0    0.0    73.0   1937.000000  229.666667  172.666667  130.666667  N
10    allenbe01  25583.0  14.0   1139.0  3404.0   357.0   815.0   140.0  21.0   73.0   351.0   13.0   16.0   370.0   424.0   52.0   8.0    24.0   17.0   60.0   161.0  1979.000000  432.000000  324.000000  0.000000    N
11    allendi01  29550.0  15.0   1749.0  6332.0   1099.0  1848.0  320.0  79.0   351.0  1119.0  133.0  52.0   894.0   1556.0  138.0  16.0   19.0   53.0   164.0  399.0  1990.428571  434.285714  326.000000  56.214286   N
12    allenjo02  29078.0  17.0   365.0   716.0    82.0    124.0   12.0   3.0    4.0    64.0    1.0    0.0    33.0    155.0   0.0    0.0    36.0   0.0    8.0    15.0   1955.000000  251.000000  189.000000  1.000000    N
13    alleyge01  21648.0  11.0   1195.0  3927.0   442.0   999.0   140.0  44.0   55.0   342.0   63.0   30.0   300.0   622.0   62.0   27.0   56.0   22.0   95.0   184.0  1979.000000  432.000000  324.000000  0.000000    N
14    allisdo01  22503.0  14.0   318.0   1407.0   236.0   381.0   43.0   10.0   2.0    140.0   5.0    2.0    22.0    40.0    0.0    0.0    0.0    0.0    0.0    53.0   1936.000000  78.000000   59.000000   1.000000    N
15    alomaro01  37939.0  21.0   2379.0  9073.0   1508.0  2724.0  504.0  80.0   210.0  1134.0  474.0  114.0  1032.0  1140.0  62.0   50.0   148.0  97.0   206.0  584.0  2010.500000  560.000000  420.500000  460.000000  Y
16    alomasa02  43958.0  24.0   1377.0  4530.0   520.0   1236.0  249.0  10.0   112.0  588.0   25.0   24.0   212.0   499.0   15.0   41.0   48.0   34.0   132.0  259.0  2013.000000  569.000000  427.000000  16.000000   N
17    aloufe01   37366.0  21.0   2082.0  7339.0   985.0   2101.0  359.0  49.0   206.0  852.0   107.0  67.0   423.0   706.0   67.0   57.0   33.0   56.0   135.0  408.0  1980.000000  385.000000  289.000000  3.000000    N
18    alouje01   31527.0  17.0   1380.0  4345.0   448.0   1216.0  170.0  26.0   32.0   377.0   31.0   46.0   138.0   267.0   32.0   30.0   44.0   20.0   143.0  196.0  1985.000000  395.000000  297.000000  1.000000    N
19    alouma01   33450.0  19.0   1667.0  5789.0   780.0   1777.0  236.0  50.0   31.0   427.0   156.0  80.0   311.0   377.0   38.0   36.0   55.0   29.0   101.0  286.0  1980.000000  385.000000  289.000000  5.000000    N
20    aloumo01   35981.0  19.0   1942.0  7037.0   1109.0  2134.0  421.0  39.0   332.0  1287.0  106.0  37.0   737.0   894.0   91.0   48.0   9.0    82.0   195.0  460.0  2014.000000  571.000000  429.000000  6.000000    N
22    altroni01  40162.0  23.0   230.0   550.0    52.0    97.0    9.0    1.0    2.0    27.0    5.0    1.0    29.0    0.0     0.0    11.0   15.0   0.0    0.0    10.0   1949.375000  247.625000  186.000000  7.250000    N
23    anderbr01  31913.0  17.0   1834.0  6499.0   1062.0  1661.0  338.0  67.0   210.0  761.0   315.0  100.0  960.0   1190.0  59.0   154.0  74.0   50.0   65.0   405.0  2008.000000  543.000000  408.000000  0.000000    N
24    anderga01  34034.0  17.0   2228.0  8640.0   1084.0  2529.0  522.0  36.0   287.0  1365.0  80.0   47.0   429.0   1224.0  104.0  8.0    13.0   87.0   197.0  558.0  2016.000000  440.000000  330.000000  1.000000    N
26    ansonca01  50868.0  27.0   2523.0  10277.0  1996.0  3418.0  581.0  142.0  97.0   2076.0  276.0  16.0   983.0   302.0   0.0    32.0   27.0   0.0    0.0    723.0  1937.500000  78.000000   59.000000   39.000000   N
27    aparilu01  35361.0  18.0   2601.0  10230.0  1335.0  2677.0  394.0  92.0   83.0   791.0   506.0  136.0  736.0   742.0   22.0   27.0   161.0  76.0   184.0  486.0  1981.500000  401.666667  301.666667  193.166667  N
28    appieke01  35946.0  20.0   414.0   83.0     4.0     8.0     0.0    0.0    0.0    4.0     0.0    0.0    1.0     39.0    0.0    1.0    5.0    0.0    0.0    0.0    2010.000000  539.000000  405.000000  1.000000    N
29    applilu01  38796.0  20.0   2422.0  8856.0   1319.0  2749.0  440.0  102.0  45.0   1116.0  179.0  108.0  1302.0  528.0   0.0    11.0   74.0   0.0    129.0  542.0  1959.000000  225.625000  172.142857  68.375000   N
30    archeji01  26782.0  17.0   847.0   2646.0   246.0   660.0   106.0  34.0   16.0   296.0   36.0   6.0    124.0   241.0   0.0    19.0   93.0   0.0    0.0    140.0  1938.000000  245.666667  184.666667  5.333333    N
31    ashburi01  29325.0  15.0   2189.0  8365.0   1322.0  2574.0  317.0  109.0  29.0   586.0   234.0  92.0   1198.0  571.0   25.0   43.0   112.0  18.0   83.0   426.0  1976.250000  371.266667  278.733333  74.600000   N
...         ...      ...   ...      ...     ...      ...     ...    ...    ...   ...     ...     ...   ...      ...    ...    ...    ...     ...   ...    ...     ...          ...         ...         ...        ...  ..
1162  winfida01  45633.0  24.0   2973.0  11003.0  1669.0  3110.0  540.0  88.0   465.0  1833.0  223.0  96.0   1216.0  1686.0  172.0  25.0   19.0   95.0   319.0  628.0  2001.000000  515.000000  387.000000  435.000000  Y
1163  winnra01   30067.0  17.0   1717.0  6186.0   863.0   1759.0  367.0  59.0   110.0  662.0   215.0  84.0   526.0   1010.0  23.0   53.0   58.0   55.0   98.0   426.0  2016.000000  440.000000  330.000000  0.000000    N
1164  wiseri01   35522.0  18.0   511.0   668.0    60.0    130.0   21.0   5.0    15.0   66.0    0.0    0.0    27.0    240.0   0.0    3.0    40.0   3.0    7.0    26.0   1988.000000  427.000000  321.000000  0.000000    N
1165  wittbo01   37881.0  22.0   438.0   64.0     2.0     9.0     3.0    0.0    1.0    5.0     0.0    0.0    2.0     25.0    0.0    0.0    6.0    1.0    0.0    3.0    2007.000000  545.000000  409.000000  0.000000    N
1166  wittmi01   25829.0  14.0   341.0   0.0      0.0     0.0     0.0    0.0    0.0    0.0     0.0    0.0    0.0     0.0     0.0    0.0    0.0    0.0    0.0    0.0    1999.000000  497.000000  373.000000  0.000000    N
1167  wittwh01   19213.0  10.0   1139.0  4171.0   632.0   1195.0  144.0  62.0   18.0   302.0   78.0   41.0   489.0   309.0   0.0    7.0    104.0  0.0    0.0    206.0  1949.000000  153.000000  115.000000  1.000000    N
1168  womacto01  32010.0  20.0   1303.0  4963.0   739.0   1353.0  190.0  59.0   36.0   368.0   363.0  74.0   308.0   649.0   9.0    28.0   57.0   33.0   53.0   249.0  2012.000000  573.000000  430.000000  0.000000    N
1169  woodjo02   26809.0  14.0   696.0   1952.0   266.0   553.0   118.0  31.0   23.0   325.0   23.0   3.0    208.0   189.0   0.0    16.0   96.0   0.0    0.0    149.0  1944.222222  205.333333  154.625000  7.444444    N
1170  woodwi01   35449.0  19.0   651.0   322.0    11.0    27.0    2.0    0.0    0.0    13.0    1.0    0.0    20.0    189.0   0.0    1.0    38.0   0.0    7.0    2.0    1986.500000  418.333333  314.333333  20.500000   N
1171  worreto01  21902.0  11.0   617.0   27.0     1.0     2.0     0.0    1.0    0.0    0.0     0.0    0.0    1.0     20.0    0.0    0.0    2.0    0.0    1.0    1.0    2003.000000  496.000000  372.000000  0.000000    N
1172  wrighge01  22518.0  12.0   591.0   2875.0   665.0   867.0   126.0  61.0   11.0   330.0   41.0   16.0   67.0    119.0   0.0    0.0    0.0    0.0    0.0    187.0  1936.500000  78.000000   59.000000   6.000000    N
1173  wrighgl01  21220.0  11.0   1119.0  4153.0   584.0   1219.0  203.0  76.0   94.0   723.0   38.0   13.0   209.0   407.0   0.0    5.0    113.0  0.0    9.0    279.0  1954.000000  213.083333  160.083333  3.750000    N
1175  wyattwh01  32924.0  18.0   366.0   607.0    53.0    133.0   26.0   2.0    7.0    69.0    0.0    0.0    26.0    111.0   0.0    2.0    34.0   0.0    20.0   28.0   1958.000000  266.000000  200.000000  1.000000    N
1176  wynnea01   44890.0  23.0   796.0   1704.0   136.0   365.0   59.0   5.0    17.0   173.0   1.0    0.0    141.0   330.0   0.0    2.0    52.0   4.0    33.0   64.0   1970.500000  349.000000  261.750000  194.000000  N
1177  wynnji01   31527.0  17.0   1920.0  6653.0   1105.0  1665.0  285.0  39.0   291.0  964.0   225.0  101.0  1224.0  1427.0  84.0   27.0   32.0   74.0   117.0  324.0  1983.000000  374.000000  281.000000  0.000000    N
1178  yastrca01  45356.0  23.0   3308.0  11988.0  1816.0  3419.0  646.0  59.0   452.0  1844.0  168.0  116.0  1845.0  1393.0  190.0  40.0   13.0   105.0  323.0  705.0  1989.000000  447.000000  336.000000  423.000000  Y
1179  yeagest01  29685.0  15.0   1269.0  3584.0   357.0   816.0   118.0  16.0   102.0  410.0   14.0   18.0   342.0   726.0   64.0   27.0   33.0   28.0   93.0   134.0  1992.000000  430.000000  323.000000  2.000000    N
1180  yerkest02  15304.0  9.0    711.0   2521.0   307.0   676.0   124.0  32.0   6.0    254.0   54.0   6.0    207.0   102.0   0.0    16.0   115.0  0.0    0.0    156.0  1945.000000  247.000000  186.000000  1.000000    N
1181  yorkru01   27191.0  15.0   1603.0  5891.0   876.0   1621.0  291.0  52.0   277.0  1152.0  38.0   26.0   792.0   867.0   0.0    12.0   25.0   0.0    155.0  343.0  1963.000000  180.500000  135.500000  5.500000    N
1182  youngcy01  43722.0  24.0   918.0   2960.0   325.0   623.0   87.0   35.0   18.0   290.0   29.0   0.0    81.0    150.0   0.0    10.0   50.0   0.0    0.0    122.0  1936.333333  168.333333  126.666667  98.666667   N
1183  younger01  35991.0  21.0   1730.0  6119.0   996.0   1731.0  327.0  46.0   79.0   543.0   465.0  168.0  660.0   462.0   14.0   89.0   84.0   44.0   135.0  373.0  2012.000000  573.000000  430.000000  1.000000    N
1184  youngpe01  21319.0  12.0   730.0   2466.0   274.0   645.0   128.0  34.0   32.0   347.0   18.0   0.0    152.0   312.0   0.0    12.0   38.0   0.0    51.0   162.0  1958.000000  266.000000  200.000000  1.000000    N
1185  youngro01  19215.0  10.0   1211.0  4627.0   812.0   1491.0  236.0  93.0   42.0   592.0   153.0  83.0   550.0   390.0   0.0    37.0   119.0  0.0    0.0    329.0  1948.368421  214.166667  162.812500  27.444444   N
1186  yountro01  39670.0  20.0   2856.0  11008.0  1632.0  3142.0  583.0  126.0  251.0  1406.0  271.0  105.0  966.0   1350.0  95.0   48.0   104.0  123.0  217.0  709.0  1999.000000  497.000000  373.000000  385.000000  Y
1187  zachato01  46268.0  29.0   546.0   1122.0   79.0    254.0   28.0   12.0   6.0    112.0   0.0    1.0    62.0    261.0   0.0    2.0    46.0   0.0    7.0    40.0   1959.000000  267.500000  201.000000  1.000000    N
1188  zachrpa01  21782.0  12.0   293.0   318.0    9.0     36.0    0.0    0.0    0.0    6.0     0.0    0.0    14.0    128.0   0.0    0.0    33.0   2.0    11.0   0.0    1991.000000  443.000000  333.000000  0.000000    N
1189  zahnge01   27702.0  15.0   304.0   43.0     3.0     6.0     0.0    0.0    0.0    1.0     0.0    0.0    0.0     9.0     0.0    0.0    10.0   0.0    1.0    0.0    1991.000000  443.000000  333.000000  0.000000    N
1190  zeileto01  41934.0  27.0   2158.0  7573.0   986.0   2004.0  397.0  23.0   253.0  1110.0  53.0   51.0   945.0   1279.0  47.0   42.0   8.0    81.0   223.0  420.0  2010.000000  539.000000  405.000000  0.000000    N
1191  zimmech01  37884.0  21.0   1280.0  4546.0   617.0   1224.0  222.0  76.0   26.0   625.0   151.0  0.0    390.0   323.0   0.0    91.0   49.0   0.0    0.0    298.0  1938.000000  262.000000  197.000000  1.000000    N
1192  ziskri01   25701.0  13.0   1453.0  5144.0   681.0   1477.0  245.0  26.0   207.0  792.0   8.0    15.0   533.0   910.0   52.0   12.0   7.0    41.0   138.0  271.0  1989.000000  447.000000  336.000000  0.000000    N

[1168 rows x 26 columns]

In [153]:
playerGroup['inducted'].value_counts()

N    1115
Y    53
Name: inducted, dtype: int64

In [111]:
mlb_gb = mlb.groupby('playerID', as_index=False).sum()
mlb_gb
mlb

       playerID  yearID  stint     G     AB     R     H   2B   3B   HR     RBI     SB     CS    BB      SO    IBB   HBP     SH     SF   GIDP   XB  yearid          votedBy  ballots  needed  votes inducted category needed_note
0     aaronha01  45195   23     3298  12364  2174  3771  624  98   755  2297.0  240.0  73.0   1402  1383.0  293.0  32.0  21.0   121.0  328.0  722  1982    BBWAA            415.0    312.0   406.0  Y        Player   NaN
1     abbotji01  21932   12     263   21     0     2     0    0    0    3.0     0.0    0.0    0     10.0    0.0    0.0   3.0    0.0    1.0    0    2005    BBWAA            516.0    387.0   13.0   N        Player   NaN
2     adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1937    BBWAA            201.0    151.0   8.0    N        Player   NaN
3     adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1938    BBWAA            262.0    197.0   11.0   N        Player   NaN
4     adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1939    BBWAA            274.0    206.0   11.0   N        Player   NaN
5     adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1942    BBWAA            233.0    175.0   11.0   N        Player   NaN
6     adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1945    BBWAA            247.0    186.0   7.0    N        Player   NaN
7     adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1946    Nominating Vote  202.0   NaN      6.0    N        Player   Top 20
8     adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1947    BBWAA            161.0    121.0   22.0   N        Player   NaN
9     adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1948    BBWAA            121.0    91.0    4.0    N        Player   NaN
10    adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1949    BBWAA            153.0    115.0   5.0    N        Player   NaN
11    adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1950    BBWAA            168.0    126.0   6.0    N        Player   NaN
12    adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1951    BBWAA            226.0    170.0   12.0   N        Player   NaN
13    adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1952    BBWAA            234.0    176.0   9.0    N        Player   NaN
14    adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1953    BBWAA            264.0    198.0   17.0   N        Player   NaN
15    adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1954    BBWAA            252.0    189.0   13.0   N        Player   NaN
16    adamsba01  36411   19     482   1019   79    216   31   15   3    75.0    1.0    1.0    53    177.0   0.0    1.0   35.0   0.0    0.0    46   1955    BBWAA            251.0    189.0   24.0   N        Player   NaN
17    adamsbo03  29290   16     1281  4019   591   1082  188  49   37   303.0   67.0   30.0   414   447.0   1.0    17.0  78.0   5.0    62.0   237  1966    BBWAA            302.0    227.0   1.0    N        Player   NaN
18    adamssp01  26997   15     1424  5557   844   1588  249  48   9    394.0   154.0  50.0   453   223.0   0.0    28.0  136.0  0.0    14.0   297  1958    BBWAA            266.0    200.0   1.0    N        Player   NaN
19    adamssp01  26997   15     1424  5557   844   1588  249  48   9    394.0   154.0  50.0   453   223.0   0.0    28.0  136.0  0.0    14.0   297  1960    BBWAA            269.0    202.0   1.0    N        Player   NaN
20    ageeto01   25583   14     1129  3912   558   999   170  27   130  433.0   167.0  81.0   342   918.0   26.0   34.0  21.0   15.0   99.0   197  1979    BBWAA            432.0    324.0   0.0    N        Player   NaN
21    aguilri01  37863   22     737   139    12    28    3    0    3    11.0    0.0    0.0    6     37.0    0.0    0.0   16.0   0.0    1.0    3    2006    BBWAA            520.0    390.0   3.0    N        Player   NaN
22    akerja01   27574   17     496   92     3     7     2    0    0    4.0     0.0    0.0    1     51.0    0.0    1.0   10.0   0.0    1.0    2    1980    BBWAA            385.0    289.0   0.0    N        Player   NaN
23    alexado01  45552   27     562   265    19    44    8    0    0    17.0    0.0    0.0    9     77.0    0.0    1.0   23.0   2.0    7.0    8    1995    BBWAA            460.0    345.0   0.0    N        Player   NaN
24    alexape01  40336   22     703   1810   154   378   60   13   11   163.0   3.0    5.0    77    276.0   0.0    2.0   88.0   0.0    0.0    73   1936    BBWAA            226.0    170.0   55.0   N        Player   NaN
25    alexape01  40336   22     703   1810   154   378   60   13   11   163.0   3.0    5.0    77    276.0   0.0    2.0   88.0   0.0    0.0    73   1937    BBWAA            201.0    151.0   125.0  N        Player   NaN
26    alexape01  40336   22     703   1810   154   378   60   13   11   163.0   3.0    5.0    77    276.0   0.0    2.0   88.0   0.0    0.0    73   1938    BBWAA            262.0    197.0   212.0  Y        Player   NaN
27    allenbe01  25583   14     1139  3404   357   815   140  21   73   351.0   13.0   16.0   370   424.0   52.0   8.0   24.0   17.0   60.0   161  1979    BBWAA            432.0    324.0   0.0    N        Player   NaN
28    allendi01  29550   15     1749  6332   1099  1848  320  79   351  1119.0  133.0  52.0   894   1556.0  138.0  16.0  19.0   53.0   164.0  399  1983    BBWAA            374.0    281.0   14.0   N        Player   NaN
29    allendi01  29550   15     1749  6332   1099  1848  320  79   351  1119.0  133.0  52.0   894   1556.0  138.0  16.0  19.0   53.0   164.0  399  1985    BBWAA            395.0    297.0   28.0   N        Player   NaN
...         ...    ...   ..      ...   ...    ...   ...  ...  ..   ...     ...    ...   ...   ...      ...    ...   ...   ...    ...     ...  ...   ...      ...              ...      ...    ...  ..           ...   ...
4054  youngcy01  43722   24     918   2960   325   623   87   35   18   290.0   29.0   0.0    81    150.0   0.0    10.0  50.0   0.0    0.0    122  1937    BBWAA            201.0    151.0   153.0  Y        Player   NaN
4055  younger01  35991   21     1730  6119   996   1731  327  46   79   543.0   465.0  168.0  660   462.0   14.0   89.0  84.0   44.0   135.0  373  2012    BBWAA            573.0    430.0   1.0    N        Player   NaN
4056  youngpe01  21319   12     730   2466   274   645   128  34   32   347.0   18.0   0.0    152   312.0   0.0    12.0  38.0   0.0    51.0   162  1958    BBWAA            266.0    200.0   1.0    N        Player   NaN
4057  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1936    BBWAA            226.0    170.0   10.0   N        Player   NaN
4058  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1937    BBWAA            201.0    151.0   16.0   N        Player   NaN
4059  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1938    BBWAA            262.0    197.0   40.0   N        Player   NaN
4060  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1939    BBWAA            274.0    206.0   34.0   N        Player   NaN
4061  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1942    BBWAA            233.0    175.0   44.0   N        Player   NaN
4062  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1945    BBWAA            247.0    186.0   22.0   N        Player   NaN
4063  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1946    Nominating Vote  202.0   NaN      25.0   N        Player   Top 20
4064  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1947    BBWAA            161.0    121.0   36.0   N        Player   NaN
4065  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1948    BBWAA            121.0    91.0    19.0   N        Player   NaN
4066  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1949    BBWAA            153.0    115.0   20.0   N        Player   NaN
4067  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1949    Run Off          187.0   NaN      11.0   N        Player   1st
4068  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1950    BBWAA            168.0    126.0   17.0   N        Player   NaN
4069  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1951    BBWAA            226.0    170.0   34.0   N        Player   NaN
4070  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1952    BBWAA            234.0    176.0   34.0   N        Player   NaN
4071  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1953    BBWAA            264.0    198.0   31.0   N        Player   NaN
4072  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1954    BBWAA            252.0    189.0   34.0   N        Player   NaN
4073  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1955    BBWAA            251.0    189.0   48.0   N        Player   NaN
4074  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1956    BBWAA            193.0    145.0   19.0   N        Player   NaN
4075  youngro01  19215   10     1211  4627   812   1491  236  93   42   592.0   153.0  83.0   550   390.0   0.0    37.0  119.0  0.0    0.0    329  1972    Veterans        NaN      NaN     NaN     Y        Player   NaN
4076  yountro01  39670   20     2856  11008  1632  3142  583  126  251  1406.0  271.0  105.0  966   1350.0  95.0   48.0  104.0  123.0  217.0  709  1999    BBWAA            497.0    373.0   385.0  Y        Player   NaN
4077  zachato01  46268   29     546   1122   79    254   28   12   6    112.0   0.0    1.0    62    261.0   0.0    2.0   46.0   0.0    7.0    40   1958    BBWAA            266.0    200.0   1.0    N        Player   NaN
4078  zachato01  46268   29     546   1122   79    254   28   12   6    112.0   0.0    1.0    62    261.0   0.0    2.0   46.0   0.0    7.0    40   1960    BBWAA            269.0    202.0   1.0    N        Player   NaN
4079  zachrpa01  21782   12     293   318    9     36    0    0    0    6.0     0.0    0.0    14    128.0   0.0    0.0   33.0   2.0    11.0   0    1991    BBWAA            443.0    333.0   0.0    N        Player   NaN
4080  zahnge01   27702   15     304   43     3     6     0    0    0    1.0     0.0    0.0    0     9.0     0.0    0.0   10.0   0.0    1.0    0    1991    BBWAA            443.0    333.0   0.0    N        Player   NaN
4081  zeileto01  41934   27     2158  7573   986   2004  397  23   253  1110.0  53.0   51.0   945   1279.0  47.0   42.0  8.0    81.0   223.0  420  2010    BBWAA            539.0    405.0   0.0    N        Player   NaN
4082  zimmech01  37884   21     1280  4546   617   1224  222  76   26   625.0   151.0  0.0    390   323.0   0.0    91.0  49.0   0.0    0.0    298  1938    BBWAA            262.0    197.0   1.0    N        Player   NaN
4083  ziskri01   25701   13     1453  5144   681   1477  245  26   207  792.0   8.0    15.0   533   910.0   52.0   12.0  7.0    41.0   138.0  271  1989    BBWAA            447.0    336.0   0.0    N        Player   NaN

[4084 rows x 29 columns]

In [154]:
pg = playerGroup

In [155]:
pg = pg.drop('2B', axis=1)
pg = pg.drop('3B', axis=1)
pg = pg.drop('CS', axis=1)
pg = pg.drop('SO', axis=1)
pg = pg.drop('IBB', axis=1)
pg = pg.drop('HBP', axis=1)
pg = pg.drop('SH', axis=1)
pg = pg.drop('SF', axis=1)
pg = pg.drop('GIDP', axis=1)
pg.head()

    playerID   yearID  stint       G       AB       R       H     HR     RBI     SB      BB     XB       yearid  ballots      needed       votes inducted
0  aaronha01  45195.0  23.0   3298.0  12364.0  2174.0  3771.0  755.0  2297.0  240.0  1402.0  722.0  1982.000000  415.0    312.000000  406.000000  Y
1  abbotji01  21932.0  12.0   263.0   21.0     0.0     2.0     0.0    3.0     0.0    0.0     0.0    2005.000000  516.0    387.000000  13.000000   N
2  adamsba01  36411.0  19.0   482.0   1019.0   79.0    216.0   3.0    75.0    1.0    53.0    46.0   1947.066667  216.6    163.571429  11.066667   N
3  adamsbo03  29290.0  16.0   1281.0  4019.0   591.0   1082.0  37.0   303.0   67.0   414.0   237.0  1966.000000  302.0    227.000000  1.000000    N
4  adamssp01  26997.0  15.0   1424.0  5557.0   844.0   1588.0  9.0    394.0   154.0  453.0   297.0  1959.000000  267.5    201.000000  1.000000    N

In [156]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [158]:
#Splitting data
# Import train_test_split function


X=pg[['G', 'AB', 'R', 'H','HR','BB','RBI','SB','XB']]  # Features
y=pg['inducted']  # Labels

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 70% training and 30% test

In [159]:
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)

In [160]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9458689458689459

In [163]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[328   4]
 [ 15   4]]