In [112]:
#!kaggle datasets download -d arashnic/baseballdatabank

import pandas as pd
import numpy as np

In [113]:

hallOfFame = pd.read_csv("HallOfFame.csv", sep=",", header="infer")

hallOfFame.head()
type(hallOfFame['playerID'])
hallOfFame

,playerID,yearid,votedBy,ballots,needed,votes,inducted,category,needed_note
0,cobbty01,1936,BBWAA,226.0,170.0,222.0,Y,Player,NaN
1,ruthba01,1936,BBWAA,226.0,170.0,215.0,Y,Player,NaN
2,wagneho01,1936,BBWAA,226.0,170.0,215.0,Y,Player,NaN
3,mathech01,1936,BBWAA,226.0,170.0,205.0,Y,Player,NaN
4,johnswa01,1936,BBWAA,226.0,170.0,189.0,Y,Player,NaN
5,lajoina01,1936,BBWAA,226.0,170.0,146.0,N,Player,NaN
6,speaktr01,1936,BBWAA,226.0,170.0,133.0,N,Player,NaN
7,youngcy01,1936,BBWAA,226.0,170.0,111.0,N,Player,NaN
8,hornsro01,1936,BBWAA,226.0,170.0,105.0,N,Player,NaN
9,cochrmi01,1936,BBWAA,226.0,170.0,80.0,N,Player,NaN
10,sislege01,1936,BBWAA,226.0,170.0,77.0,N,Player,NaN
11,collied01,1936,BBWAA,226.0,170.0,60.0,N,Player,NaN
12,colliji01,1936,BBWAA,226.0,170.0,58.0,N,Player,NaN
13,alexape01,1936,BBWAA,226.0,170.0,55.0,N,Player,NaN
14,gehrilo01,1936,BBWAA,226.0,170.0,51.0,N,Player,NaN
15,bresnro01,1936,BBWAA,226.0,170.0,47.0,N,Player,NaN
16,keelewi01,1936,BBWAA,226.0,170.0,40.0,N,Player,NaN
17,ansonca01,1936,Veterans,78.0,59.0,39.0,N,Player,NaN
18,ewingbu01,1936,Veterans,78.0,59.0,39.0,N,Player,NaN
19,keelewi01,1936,Veterans,78.0,59.0,33.0,N,Player,NaN
20,wadderu01,1936,BBWAA,226.0,170.0,33.0,N,Player,NaN
21,youngcy01,1936,Veterans,78.0,59.0,32.0,N,Player,NaN
22,delahed01,1936,Veterans,78.0,59.0,21.0,N,Player,NaN
23,foxxji01,1936,BBWAA,226.0,170.0,21.0,N,Player,NaN
24,walshed01,1936,BBWAA,226.0,170.0,20.0,N,Player,NaN
25,mcgrajo01,1936,Veterans,78.0,59.0,17.0,N,Player,NaN
26,delahed01,1936,BBWAA,226.0,170.0,17.0,N,Player,NaN
27,radboch01,1936,Veterans,78.0,59.0,16.0,N,Player,NaN
28,traynpi01,1936,BBWAA,226.0,170.0,16.0,N,Player,NaN
29,kellyki01,1936,Veterans,78.0,59.0,15.0,N,Player,NaN
...,...,...,...,...,...,...,...,...,...
4126,clemero02,2017,BBWAA,442.0,332.0,239.0,N,Player,NaN
4127,bondsba01,2017,BBWAA,442.0,332.0,238.0,N,Player,NaN
4128,mussimi01,2017,BBWAA,442.0,332.0,229.0,N,Player,NaN
4129,schilcu01,2017,BBWAA,442.0,332.0,199.0,N,Player,NaN
4130,smithle02,2017,BBWAA,442.0,332.0,151.0,N,Player,NaN
4131,ramirma02,2017,BBWAA,442.0,332.0,105.0,N,Player,NaN
4132,walkela01,2017,BBWAA,442.0,332.0,97.0,N,Player,NaN
4133,mcgrifr01,2017,BBWAA,442.0,332.0,96.0,N,Player,NaN
4134,kentje01,2017,BBWAA,442.0,332.0,74.0,N,Player,NaN
4135,sheffga01,2017,BBWAA,442.0,332.0,59.0,N,Player,NaN
4136,wagnebi02,2017,BBWAA,442.0,332.0,45.0,N,Player,NaN
4137,sosasa01,2017,BBWAA,442.0,332.0,38.0,N,Player,NaN
4138,posadjo01,2017,BBWAA,442.0,332.0,17.0,N,Player,NaN
4139,ordonma01,2017,BBWAA,442.0,332.0,3.0,N,Player,NaN
4140,varitja01,2017,BBWAA,442.0,332.0,2.0,N,Player,NaN
4141,renteed01,2017,BBWAA,442.0,332.0,2.0,N,Player,NaN
4142,wakefti01,2017,BBWAA,442.0,332.0,1.0,N,Player,NaN
4143,morame01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4144,camermi01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4145,rhodear01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4146,sanchfr01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4147,cabreor01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4148,drewj.01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4149,leede02,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4150,blakeca01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4151,guillca01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4152,burrepa01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4153,stairma01,2017,BBWAA,442.0,332.0,0.0,N,Player,NaN
4154,seligbu99,2017,Veterans,NaN,NaN,NaN,Y,Pioneer/Executive,NaN
4155,schurjo99,2017,Veterans,NaN,NaN,NaN,Y,Pioneer/Executive,NaN

In [114]:
hallOfFame.shape

(4156, 9)

In [115]:
hallOfFame.describe().T

,count,mean,std,min,25%,50%,75%,max
yearid,4156.0,1969.306304,23.231639,1936.0,1950.0,1966.0,1988.0,2017.0
ballots,3961.0,321.746529,125.455368,78.0,226.0,274.0,427.0,581.0
needed,3804.0,244.776551,94.497219,59.0,175.0,213.0,323.0,436.0
votes,3961.0,51.465791,85.473954,0.0,2.0,10.0,64.0,555.0

In [116]:
hallOfFame.dtypes

playerID        object
yearid           int64
votedBy         object
ballots        float64
needed         float64
votes          float64
inducted        object
category        object
needed_note     object
dtype: object

In [117]:
cols_obj = [cols for cols in hallOfFame.columns if str(hallOfFame[cols].dtype)=="object" ]

cols_obj

hallOfFame[cols_obj].describe().T

            count unique        top  freq
playerID     4156   1260  roushed01    20
votedBy      4156      9      BBWAA  3723
inducted     4156      2          N  3839
category     4156      4     Player  4031
needed_note   157      2        1st    81

In [118]:
hallOfFame.isnull().sum()

playerID          0
yearid            0
votedBy           0
ballots         195
needed          352
votes           195
inducted          0
category          0
needed_note    3999
dtype: int64

In [119]:
batting = pd.read_csv("Batting.csv", header= "infer", sep=",")

batting.head()

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,1871,1,TRO,NaN,1,4,0,0,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,1871,1,RC1,NaN,25,118,30,32,6,...,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,NaN
2,allisar01,1871,1,CL1,NaN,29,137,28,40,4,...,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,NaN
3,allisdo01,1871,1,WS3,NaN,27,133,28,44,10,...,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,NaN
4,ansonca01,1871,1,RC1,NaN,25,120,29,39,11,...,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,NaN

In [120]:
batting.shape

(102816, 22)

In [121]:
batting.describe().T

,count,mean,std,min,25%,50%,75%,max
yearID,102816.0,1964.262313,38.856297,1871.0,1934.0,1973.0,1998.0,2016.0
stint,102816.0,1.077838,0.284366,1.0,1.0,1.0,1.0,5.0
G,102816.0,51.343439,47.121658,1.0,13.0,34.0,80.0,165.0
AB,102816.0,141.905511,184.654492,0.0,4.0,49.0,231.0,716.0
R,102816.0,18.815544,28.242983,0.0,0.0,4.0,27.0,192.0
H,102816.0,37.139930,52.603757,0.0,0.0,9.0,58.0,262.0
2B,102816.0,6.289167,9.662468,0.0,0.0,1.0,9.0,67.0
3B,102816.0,1.293252,2.645770,0.0,0.0,0.0,1.0,36.0
HR,102816.0,2.813599,6.304919,0.0,0.0,0.0,2.0,73.0
RBI,102392.0,17.003975,26.352011,0.0,0.0,3.0,24.0,191.0
SB,101516.0,2.976821,7.717174,0.0,0.0,0.0,2.0,138.0
CS,79360.0,1.226008,2.747377,0.0,0.0,0.0,1.0,42.0
BB,102816.0,13.067207,20.746460,0.0,0.0,3.0,18.0,232.0
SO,94978.0,20.529712,28.328542,0.0,1.0,9.0,29.0,223.0
IBB,66251.0,1.105870,2.780187,0.0,0.0,0.0,1.0,120.0
HBP,100006.0,1.056057,2.276251,0.0,0.0,0.0,1.0,51.0
SH,96478.0,2.299540,4.241095,0.0,0.0,0.0,3.0,67.0
SF,66782.0,1.054101,1.961732,0.0,0.0,0.0,1.0,19.0
GIDP,76706.0,2.981018,4.735153,0.0,0.0,0.0,4.0,36.0

In [122]:
batting.dtypes

playerID     object
yearID        int64
stint         int64
teamID       object
lgID         object
G             int64
AB            int64
R             int64
H             int64
2B            int64
3B            int64
HR            int64
RBI         float64
SB          float64
CS          float64
BB            int64
SO          float64
IBB         float64
HBP         float64
SH          float64
SF          float64
GIDP        float64
dtype: object

In [123]:
cols_obj = [cols for cols in batting.columns if str(batting[cols].dtype)=="object" ]

cols_obj

batting[cols_obj].describe().T

           count unique        top   freq
playerID  102816  18915  mcguide01     31
teamID    102816    149        CHN   4863
lgID      102079      6         NL  52134

In [124]:
batting.isnull().sum()

playerID        0
yearID          0
stint           0
teamID          0
lgID          737
G               0
AB              0
R               0
H               0
2B              0
3B              0
HR              0
RBI           424
SB           1300
CS          23456
BB              0
SO           7838
IBB         36565
HBP          2810
SH           6338
SF          36034
GIDP        26110
dtype: int64

In [125]:
pitching = pd.read_csv("Pitching.csv", sep=",", header="infer")

pitching.head()

,playerID,yearID,stint,teamID,lgID,W,L,G,GS,CG,...,IBB,WP,HBP,BK,BFP,GF,R,SH,SF,GIDP
0,bechtge01,1871,1,PH1,NaN,1,2,3,3,2,...,NaN,NaN,NaN,0,NaN,NaN,42,NaN,NaN,NaN
1,brainas01,1871,1,WS3,NaN,12,15,30,30,30,...,NaN,NaN,NaN,0,NaN,NaN,292,NaN,NaN,NaN
2,fergubo01,1871,1,NY2,NaN,0,0,1,0,0,...,NaN,NaN,NaN,0,NaN,NaN,9,NaN,NaN,NaN
3,fishech01,1871,1,RC1,NaN,4,16,24,24,22,...,NaN,NaN,NaN,0,NaN,NaN,257,NaN,NaN,NaN
4,fleetfr01,1871,1,NY2,NaN,0,1,1,1,1,...,NaN,NaN,NaN,0,NaN,NaN,21,NaN,NaN,NaN

In [126]:
pitching.shape

(44963, 30)

In [127]:
pitching.describe().T

,count,mean,std,min,25%,50%,75%,max
yearID,44963.0,1968.670062,37.569499,1871.0,1941.000,1978.00,2001.000,2016.00
stint,44963.0,1.079643,0.284834,1.0,1.000,1.00,1.000,4.00
W,44963.0,4.715744,5.813410,0.0,0.000,2.00,7.000,59.00
L,44963.0,4.715722,4.988846,0.0,1.000,3.00,8.000,48.00
G,44963.0,23.681761,18.493488,1.0,7.000,21.00,35.000,106.00
GS,44963.0,9.485488,12.283920,0.0,0.000,3.00,17.000,75.00
CG,44963.0,3.151035,7.081844,0.0,0.000,0.00,3.000,75.00
SHO,44963.0,0.448591,1.109742,0.0,0.000,0.00,0.000,16.00
SV,44963.0,1.504793,4.991518,0.0,0.000,0.00,1.000,62.00
IPouts,44963.0,253.872139,257.330446,0.0,49.000,167.00,393.000,2040.00
H,44963.0,84.912439,84.589269,0.0,18.000,55.00,134.000,772.00
ER,44963.0,36.103863,33.431186,0.0,9.000,25.00,58.000,291.00
HR,44963.0,6.434201,6.988237,0.0,1.000,4.00,9.000,50.00
BB,44963.0,29.905300,28.172268,0.0,8.000,21.00,45.000,289.00
SO,44963.0,46.500856,49.345046,0.0,8.000,31.00,68.000,513.00
BAOpp,43437.0,0.319920,0.710482,0.0,0.236,0.26,0.298,9.99
ERA,44874.0,5.073269,5.318781,0.0,3.150,4.14,5.510,189.00
IBB,30388.0,2.411379,2.772648,0.0,0.000,2.00,4.000,23.00
WP,44830.0,2.528575,3.425706,0.0,0.000,1.00,4.000,63.00
HBP,44405.0,2.266096,2.998881,0.0,0.000,1.00,3.000,41.00
BK,44963.0,0.301604,0.755523,0.0,0.000,0.00,0.000,16.00
BFP,44724.0,343.312181,348.758261,0.0,64.000,227.00,535.000,2906.00
GF,44830.0,6.345260,9.993949,0.0,0.000,3.00,8.000,84.00
R,44963.0,43.021773,43.245812,0.0,11.000,28.00,67.000,519.00
SH,12063.0,2.141922,2.710191,0.0,0.000,1.00,3.000,21.00
SF,12063.0,1.878388,2.121352,0.0,0.000,1.00,3.000,14.00
GIDP,12061.0,5.322610,5.990178,0.0,1.000,3.00,8.000,40.00

In [128]:
pitching.dtypes

playerID     object
yearID        int64
stint         int64
teamID       object
lgID         object
W             int64
L             int64
G             int64
GS            int64
CG            int64
SHO           int64
SV            int64
IPouts        int64
H             int64
ER            int64
HR            int64
BB            int64
SO            int64
BAOpp       float64
ERA         float64
IBB         float64
WP          float64
HBP         float64
BK            int64
BFP         float64
GF          float64
R             int64
SH          float64
SF          float64
GIDP        float64
dtype: object

In [129]:
cols_obj = [cols for cols in pitching.columns if str(pitching[cols].dtype) =="object"]

cols_obj

pitching[cols_obj].describe().T

          count unique        top   freq
playerID  44963   9302  newsobo01     29
teamID    44963    149        PHI   2117
lgID      44832      6         NL  22823

In [130]:
pitching.isnull().sum()

playerID        0
yearID          0
stint           0
teamID          0
lgID          131
W               0
L               0
G               0
GS              0
CG              0
SHO             0
SV              0
IPouts          0
H               0
ER              0
HR              0
BB              0
SO              0
BAOpp        1526
ERA            89
IBB         14575
WP            133
HBP           558
BK              0
BFP           239
GF            133
R               0
SH          32900
SF          32900
GIDP        32902
dtype: int64

In [137]:
batting

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,1871,1,TRO,NaN,1,4,0,0,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,1871,1,RC1,NaN,25,118,30,32,6,...,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,NaN
2,allisar01,1871,1,CL1,NaN,29,137,28,40,4,...,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,NaN
3,allisdo01,1871,1,WS3,NaN,27,133,28,44,10,...,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,NaN
4,ansonca01,1871,1,RC1,NaN,25,120,29,39,11,...,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,NaN
5,armstbo01,1871,1,FW1,NaN,12,49,9,11,2,...,5.0,0.0,1.0,0,1.0,NaN,NaN,NaN,NaN,NaN
6,barkeal01,1871,1,RC1,NaN,1,4,0,1,0,...,2.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
7,barnero01,1871,1,BS1,NaN,31,157,66,63,10,...,34.0,11.0,6.0,13,1.0,NaN,NaN,NaN,NaN,NaN
8,barrebi01,1871,1,FW1,NaN,1,5,1,1,1,...,1.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
9,barrofr01,1871,1,BS1,NaN,18,86,13,13,2,...,11.0,1.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
10,bassjo01,1871,1,CL1,NaN,22,89,18,27,1,...,18.0,0.0,1.0,3,4.0,NaN,NaN,NaN,NaN,NaN
11,battijo01,1871,1,CL1,NaN,1,3,0,0,0,...,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
12,bealsto01,1871,1,WS3,NaN,10,36,6,7,0,...,1.0,2.0,0.0,2,0.0,NaN,NaN,NaN,NaN,NaN
13,beaveed01,1871,1,TRO,NaN,3,15,7,6,0,...,5.0,2.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
14,bechtge01,1871,1,PH1,NaN,20,94,24,33,9,...,21.0,4.0,0.0,2,2.0,NaN,NaN,NaN,NaN,NaN
15,bellast01,1871,1,TRO,NaN,29,128,26,32,3,...,23.0,4.0,4.0,9,2.0,NaN,NaN,NaN,NaN,NaN
16,berkena01,1871,1,PH1,NaN,1,4,0,0,0,...,0.0,0.0,0.0,0,3.0,NaN,NaN,NaN,NaN,NaN
17,berryto01,1871,1,PH1,NaN,1,4,0,1,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
18,berthha01,1871,1,WS3,NaN,17,73,17,17,1,...,8.0,3.0,1.0,4,2.0,NaN,NaN,NaN,NaN,NaN
19,biermch01,1871,1,FW1,NaN,1,2,0,0,0,...,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
20,birdge01,1871,1,RC1,NaN,25,106,19,28,2,...,13.0,1.0,0.0,3,2.0,NaN,NaN,NaN,NaN,NaN
21,birdsda01,1871,1,BS1,NaN,29,152,51,46,3,...,24.0,6.0,0.0,4,4.0,NaN,NaN,NaN,NaN,NaN
22,brainas01,1871,1,WS3,NaN,30,134,24,30,4,...,21.0,4.0,0.0,7,2.0,NaN,NaN,NaN,NaN,NaN
23,brannmi01,1871,1,CH1,NaN,3,14,2,1,0,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
24,burrohe01,1871,1,WS3,NaN,12,63,11,15,2,...,14.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN,NaN
25,careyto01,1871,1,FW1,NaN,19,87,16,20,2,...,10.0,5.0,0.0,2,1.0,NaN,NaN,NaN,NaN,NaN
26,carleji01,1871,1,CL1,NaN,29,127,31,32,8,...,18.0,2.0,1.0,8,3.0,NaN,NaN,NaN,NaN,NaN
27,conefr01,1871,1,BS1,NaN,19,77,17,20,3,...,16.0,12.0,1.0,8,2.0,NaN,NaN,NaN,NaN,NaN
28,connone01,1871,1,TRO,NaN,7,33,6,7,0,...,2.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
29,cravebi01,1871,1,TRO,NaN,27,118,26,38,8,...,26.0,6.0,3.0,3,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102786,wittgni01,2016,1,MIA,NL,48,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102787,wolteto01,2016,1,COL,NL,71,205,27,53,15,...,30.0,4.0,1.0,21,53.0,2.0,0.0,4.0,0.0,1.0
102788,wongko01,2016,1,SLN,NL,121,313,39,75,7,...,23.0,7.0,0.0,34,52.0,2.0,9.0,0.0,5.0,3.0
102789,woodal02,2016,1,LAN,NL,15,16,2,4,0,...,2.0,0.0,0.0,1,9.0,0.0,0.0,2.0,0.0,0.0
102790,woodbl01,2016,1,CIN,NL,70,2,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102791,woodtr01,2016,1,CHN,NL,81,11,0,2,0,...,1.0,0.0,0.0,1,5.0,0.0,0.0,0.0,0.0,0.0
102792,worleva01,2016,1,BAL,AL,35,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102793,worthda01,2016,1,HOU,AL,16,39,4,7,2,...,1.0,0.0,0.0,1,6.0,0.0,0.0,0.0,0.0,1.0
102794,wrighda03,2016,1,NYN,NL,37,137,18,31,8,...,14.0,3.0,2.0,26,55.0,0.0,0.0,0.0,0.0,0.0
102795,wrighda04,2016,1,CIN,NL,4,5,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102796,wrighda04,2016,2,LAA,AL,5,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102797,wrighmi01,2016,1,BAL,AL,18,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102798,wrighst01,2016,1,BOS,AL,25,4,0,0,0,...,0.0,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0
102799,yateski01,2016,1,NYA,AL,41,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102800,yelicch01,2016,1,MIA,NL,155,578,78,172,38,...,98.0,9.0,4.0,72,138.0,4.0,4.0,0.0,5.0,20.0
102801,ynoaga01,2016,1,NYN,NL,10,3,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102802,ynoami01,2016,1,CHA,AL,23,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102803,ynoara01,2016,1,COL,NL,3,5,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102804,youngch03,2016,1,KCA,AL,34,1,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102805,youngch04,2016,1,BOS,AL,76,203,29,56,18,...,24.0,4.0,2.0,21,50.0,0.0,3.0,0.0,0.0,4.0
102806,younger03,2016,1,NYA,AL,6,1,2,0,0,...,0.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102807,youngma03,2016,1,ATL,NL,8,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102808,zastrro01,2016,1,CHN,NL,8,3,0,0,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102809,zieglbr01,2016,1,ARI,NL,36,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102810,zieglbr01,2016,2,BOS,AL,33,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102811,zimmejo02,2016,1,DET,AL,19,4,0,1,0,...,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102812,zimmery01,2016,1,WAS,NL,115,427,60,93,18,...,46.0,4.0,1.0,29,104.0,1.0,5.0,0.0,6.0,12.0
102813,zobribe01,2016,1,CHN,NL,147,523,94,142,31,...,76.0,6.0,4.0,96,82.0,6.0,4.0,4.0,4.0,17.0
102814,zuninmi01,2016,1,SEA,AL,55,164,16,34,7,...,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0
102815,zychto01,2016,1,SEA,AL,12,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [132]:
batting.isnull().sum()

playerID        0
yearID          0
stint           0
teamID          0
lgID          737
G               0
AB              0
R               0
H               0
2B              0
3B              0
HR              0
RBI           424
SB           1300
CS          23456
BB              0
SO           7838
IBB         36565
HBP          2810
SH           6338
SF          36034
GIDP        26110
dtype: int64

In [ ]:
###################################################################################################################
###################################################################################################################
###################################################################################################################
###################################################################################################################
###################################################################################################################

In [180]:
battingdata = batting.groupby('playerID', as_index=False).sum()
battingdata.isnull().sum()
#batting.isnull().sum()

playerID    0
yearID      0
stint       0
G           0
AB          0
R           0
H           0
2B          0
3B          0
HR          0
RBI         0
SB          0
CS          0
BB          0
SO          0
IBB         0
HBP         0
SH          0
SF          0
GIDP        0
dtype: int64

In [181]:
battingdata.count()

playerID    18915
yearID      18915
stint       18915
G           18915
AB          18915
R           18915
H           18915
2B          18915
3B          18915
HR          18915
RBI         18915
SB          18915
CS          18915
BB          18915
SO          18915
IBB         18915
HBP         18915
SH          18915
SF          18915
GIDP        18915
dtype: int64

In [182]:
battingdata.head()

,playerID,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,18084,9,331,4,0,0,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
1,aaronha01,45195,23,3298,12364,2174,3771,624,98,755,2297.0,240.0,73.0,1402,1383.0,293.0,32.0,21.0,121.0,328.0
2,aaronto01,13768,7,437,944,102,216,42,6,13,94.0,9.0,8.0,86,145.0,3.0,0.0,9.0,6.0,36.0
3,aasedo01,25786,13,448,5,0,0,0,0,0,0.0,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0
4,abadan01,6010,3,15,21,1,2,0,0,0,0.0,0.0,1.0,4,5.0,0.0,0.0,0.0,0.0,1.0

In [183]:
battingdata.describe().T

,count,mean,std,min,25%,50%,75%,max
yearID,18915.0,10677.113085,9959.489812,1871.0,2015.0,6042.0,15959.5,58823.0
stint,18915.0,5.858789,5.621206,1.0,1.0,4.0,9.0,39.0
G,18915.0,279.086809,453.824217,1.0,13.0,78.0,329.0,3562.0
AB,18915.0,771.353793,1603.985998,0.0,6.0,71.0,603.0,14053.0
R,18915.0,102.275390,238.578514,0.0,0.0,6.0,63.0,2295.0
H,18915.0,201.880994,450.549938,0.0,1.0,12.0,133.0,4256.0
2B,18915.0,34.185937,79.835905,0.0,0.0,2.0,21.0,792.0
3B,18915.0,7.029712,18.905794,0.0,0.0,0.0,4.0,309.0
HR,18915.0,15.293841,50.240622,0.0,0.0,0.0,4.0,762.0
RBI,18915.0,92.047105,222.361516,0.0,0.0,4.0,54.0,2297.0
SB,18915.0,15.976474,54.707079,0.0,0.0,0.0,5.0,1406.0
CS,18915.0,5.143854,16.352069,0.0,0.0,0.0,1.0,335.0
BB,18915.0,71.029236,175.079949,0.0,0.0,4.0,40.0,2558.0
SO,18915.0,103.085964,226.909601,0.0,1.0,11.0,89.0,2597.0
IBB,18915.0,3.873381,16.743993,0.0,0.0,0.0,0.0,688.0
HBP,18915.0,5.583505,15.570065,0.0,0.0,0.0,3.0,287.0
SH,18915.0,11.729051,28.469311,0.0,0.0,1.0,10.0,512.0
SF,18915.0,3.721649,12.085521,0.0,0.0,0.0,0.0,128.0
GIDP,18915.0,12.088924,33.423978,0.0,0.0,0.0,4.0,350.0

In [184]:
# Checking if playerID values appear uniquely

In [185]:
battingdata[battingdata['playerID']=='cobbty01']

,playerID,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
3155,cobbty01,45996,24,3035,11434,2246,4189,724,295,117,1937.0,892.0,178.0,1249,357.0,0.0,94.0,295.0,0.0,0.0

In [186]:
batting[batting['playerID']=='cobbty01']

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
9840,cobbty01,1905,1,DET,AL,41,150,19,36,6,...,15.0,2.0,NaN,10,NaN,NaN,0.0,4.0,NaN,NaN
10243,cobbty01,1906,1,DET,AL,98,358,45,113,15,...,34.0,23.0,NaN,19,NaN,NaN,3.0,14.0,NaN,NaN
10699,cobbty01,1907,1,DET,AL,150,605,97,212,28,...,119.0,49.0,NaN,24,NaN,NaN,5.0,12.0,NaN,NaN
11140,cobbty01,1908,1,DET,AL,150,581,88,188,36,...,108.0,39.0,NaN,34,NaN,NaN,6.0,14.0,NaN,NaN
11627,cobbty01,1909,1,DET,AL,156,573,116,216,33,...,107.0,76.0,NaN,48,NaN,NaN,6.0,24.0,NaN,NaN
12166,cobbty01,1910,1,DET,AL,140,506,106,194,35,...,91.0,65.0,NaN,64,NaN,NaN,4.0,16.0,NaN,NaN
12708,cobbty01,1911,1,DET,AL,146,591,147,248,47,...,127.0,83.0,NaN,44,NaN,NaN,8.0,11.0,NaN,NaN
13282,cobbty01,1912,1,DET,AL,140,553,120,226,30,...,83.0,61.0,NaN,43,NaN,NaN,5.0,8.0,NaN,NaN
13921,cobbty01,1913,1,DET,AL,122,428,70,167,18,...,67.0,51.0,NaN,58,31.0,NaN,4.0,11.0,NaN,NaN
14568,cobbty01,1914,1,DET,AL,98,345,69,127,22,...,57.0,35.0,17.0,57,22.0,NaN,6.0,6.0,NaN,NaN
15352,cobbty01,1915,1,DET,AL,156,563,144,208,31,...,99.0,96.0,38.0,118,43.0,NaN,10.0,9.0,NaN,NaN
16105,cobbty01,1916,1,DET,AL,145,542,113,201,31,...,68.0,68.0,24.0,78,39.0,NaN,2.0,14.0,NaN,NaN
16653,cobbty01,1917,1,DET,AL,152,588,107,225,44,...,102.0,55.0,NaN,61,34.0,NaN,4.0,16.0,NaN,NaN
17174,cobbty01,1918,1,DET,AL,111,421,83,161,19,...,64.0,34.0,NaN,41,21.0,NaN,2.0,9.0,NaN,NaN
17680,cobbty01,1919,1,DET,AL,124,497,92,191,36,...,70.0,28.0,NaN,38,22.0,NaN,1.0,9.0,NaN,NaN
18208,cobbty01,1920,1,DET,AL,112,428,86,143,28,...,63.0,15.0,10.0,58,28.0,NaN,2.0,7.0,NaN,NaN
18721,cobbty01,1921,1,DET,AL,128,507,124,197,37,...,101.0,22.0,15.0,56,19.0,NaN,3.0,15.0,NaN,NaN
19240,cobbty01,1922,1,DET,AL,137,526,99,211,42,...,99.0,9.0,13.0,55,24.0,NaN,4.0,27.0,NaN,NaN
19763,cobbty01,1923,1,DET,AL,145,556,103,189,40,...,88.0,9.0,10.0,66,14.0,NaN,3.0,22.0,NaN,NaN
20292,cobbty01,1924,1,DET,AL,155,625,115,211,38,...,78.0,23.0,14.0,85,18.0,NaN,1.0,15.0,NaN,NaN
20841,cobbty01,1925,1,DET,AL,121,415,97,157,31,...,102.0,13.0,9.0,65,12.0,NaN,5.0,5.0,NaN,NaN
21395,cobbty01,1926,1,DET,AL,79,233,48,79,18,...,62.0,9.0,4.0,26,2.0,NaN,1.0,13.0,NaN,NaN
21935,cobbty01,1927,1,PHA,AL,134,490,104,175,32,...,93.0,22.0,16.0,67,12.0,NaN,5.0,12.0,NaN,NaN
22476,cobbty01,1928,1,PHA,AL,95,353,54,114,27,...,40.0,5.0,8.0,34,16.0,NaN,4.0,2.0,NaN,NaN

In [187]:
battingdata[battingdata['playerID']=='aardsda01']

,playerID,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,18084,9,331,4,0,0,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0

In [188]:
batting[batting['playerID']=='aardsda01']

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,2B,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
84639,aardsda01,2004,1,SFN,NL,11,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
87315,aardsda01,2006,1,CHN,NL,45,2,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
88692,aardsda01,2007,1,CHA,AL,25,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
90077,aardsda01,2008,1,BOS,AL,47,1,0,0,0,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
91462,aardsda01,2009,1,SEA,AL,73,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
92850,aardsda01,2010,1,SEA,AL,53,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95595,aardsda01,2012,1,NYA,AL,1,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
97003,aardsda01,2013,1,NYN,NL,43,0,0,0,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
99847,aardsda01,2015,1,ATL,NL,33,1,0,0,0,...,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0

In [189]:
battingdata

,playerID,yearID,stint,G,AB,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,18084,9,331,4,0,0,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
1,aaronha01,45195,23,3298,12364,2174,3771,624,98,755,2297.0,240.0,73.0,1402,1383.0,293.0,32.0,21.0,121.0,328.0
2,aaronto01,13768,7,437,944,102,216,42,6,13,94.0,9.0,8.0,86,145.0,3.0,0.0,9.0,6.0,36.0
3,aasedo01,25786,13,448,5,0,0,0,0,0,0.0,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0
4,abadan01,6010,3,15,21,1,2,0,0,0,0.0,0.0,1.0,4,5.0,0.0,0.0,0.0,0.0,1.0
5,abadfe01,16107,9,315,9,0,1,0,0,0,0.0,0.0,0.0,0,5.0,0.0,0.0,0.0,0.0,1.0
6,abadijo01,3750,3,12,49,4,11,0,0,0,5.0,1.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0
7,abbated01,19051,11,855,3044,355,772,99,43,11,324.0,142.0,0.0,289,16.0,0.0,33.0,93.0,0.0,0.0
8,abbeybe01,11365,7,79,225,21,38,3,3,0,17.0,3.0,0.0,21,54.0,0.0,0.0,4.0,0.0,0.0
9,abbeych01,9475,5,451,1751,307,492,67,46,19,280.0,93.0,0.0,167,105.0,0.0,23.0,18.0,0.0,0.0
10,abbotda01,1890,1,3,7,0,1,0,1,0,1.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
11,abbotfr01,5712,3,160,513,48,107,21,6,1,49.0,14.0,0.0,19,0.0,0.0,8.0,20.0,0.0,0.0
12,abbotgl01,23743,13,248,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
13,abbotje01,9995,5,233,596,82,157,33,2,18,83.0,6.0,5.0,38,91.0,2.0,3.0,5.0,7.0,12.0
14,abbotji01,21932,12,263,21,0,2,0,0,0,3.0,0.0,0.0,0,10.0,0.0,0.0,3.0,0.0,1.0
15,abbotku01,19971,11,702,2044,273,523,109,23,62,242.0,22.0,11.0,133,571.0,11.0,17.0,21.0,12.0,37.0
16,abbotky01,7974,4,57,31,2,3,1,0,0,2.0,0.0,0.0,1,19.0,0.0,0.0,6.0,0.0,0.0
17,abbotod01,1910,1,22,70,2,13,2,1,0,6.0,3.0,0.0,6,20.0,0.0,0.0,6.0,0.0,0.0
18,abbotpa01,23977,13,162,20,2,5,1,0,0,2.0,0.0,0.0,0,6.0,0.0,0.0,5.0,0.0,0.0
19,aberal01,15635,10,168,100,5,14,0,0,0,6.0,0.0,0.0,8,41.0,0.0,0.0,8.0,1.0,2.0
20,abercda01,1871,1,1,4,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
21,abercre01,6021,3,180,386,65,86,20,2,9,34.0,18.0,8.0,21,123.0,2.0,7.0,5.0,2.0,3.0
22,abernbi01,1952,1,1,1,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
23,abernbr01,10014,6,232,868,97,212,36,5,8,79.0,21.0,7.0,60,93.0,1.0,7.0,16.0,4.0,15.0
24,abernte01,5829,3,7,5,0,1,0,0,0,0.0,0.0,0.0,1,3.0,0.0,0.0,0.0,0.0,0.0
25,abernte02,33409,21,681,181,12,25,3,0,0,9.0,0.0,0.0,6,74.0,0.0,2.0,15.0,0.0,4.0
26,abernwo01,3893,2,16,8,0,0,0,0,0,0.0,0.0,0.0,0,4.0,0.0,0.0,0.0,0.0,0.0
27,aberscl01,5844,3,63,179,25,45,7,3,5,26.0,0.0,0.0,25,44.0,0.0,0.0,0.0,0.0,6.0
28,ablesha01,5725,3,14,26,0,0,0,0,0,0.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
29,abnersh01,13928,8,392,840,89,191,39,4,11,71.0,6.0,8.0,43,153.0,10.0,7.0,5.0,7.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18885,zimmejo02,16100,8,200,324,18,55,6,0,1,15.0,0.0,0.0,10,99.0,0.0,0.0,44.0,2.0,2.0
18886,zimmero01,1945,1,27,98,14,27,1,0,5,15.0,1.0,0.0,5,16.0,0.0,3.0,0.0,0.0,2.0
18887,zimmery01,24126,12,1408,5416,793,1505,338,20,215,829.0,41.0,15.0,539,1087.0,41.0,25.0,1.0,58.0,173.0
18888,zinkch01,2008,1,1,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
18889,zinkwa01,1921,1,2,1,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
18890,zinnfr01,1888,1,2,7,0,0,0,0,0,0.0,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0
18891,zinngu01,9565,5,314,1103,136,297,51,23,15,139.0,28.0,0.0,109,77.0,0.0,6.0,29.0,0.0,0.0
18892,zinnji01,9611,5,76,120,17,34,6,2,2,15.0,2.0,1.0,7,18.0,0.0,1.0,3.0,0.0,0.0
18893,zinsebi01,1944,1,2,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
18894,zinteal01,4006,2,67,78,7,13,4,0,3,9.0,0.0,0.0,5,34.0,0.0,0.0,0.0,1.0,0.0
18895,zipfebu01,3923,2,118,354,38,78,11,6,10,39.0,2.0,3.0,32,92.0,1.0,1.0,4.0,2.0,4.0
18896,ziskri01,25701,13,1453,5144,681,1477,245,26,207,792.0,8.0,15.0,533,910.0,52.0,12.0,7.0,41.0,138.0
18897,zitoba01,30106,15,434,344,12,35,0,0,0,11.0,0.0,0.0,18,99.0,0.0,0.0,56.0,0.0,4.0
18898,zitzmbi01,13473,8,406,1004,197,268,38,11,3,89.0,42.0,11.0,83,85.0,0.0,16.0,39.0,0.0,0.0
18899,zmiched01,3821,2,13,17,0,1,0,0,0,1.0,0.0,0.0,0,10.0,0.0,0.0,0.0,0.0,0.0
18900,zobribe01,24136,13,1337,4840,735,1287,296,38,145,643.0,111.0,43.0,700,839.0,32.0,26.0,23.0,55.0,97.0
18901,zoccope01,2003,1,20,37,0,4,1,0,0,3.0,0.0,0.0,2,13.0,0.0,0.0,0.0,0.0,1.0
18902,zoldasa01,19480,11,251,286,16,50,6,0,0,11.0,1.0,0.0,10,52.0,0.0,1.0,9.0,0.0,4.0
18903,zoskyed01,9977,5,44,50,4,8,1,2,0,3.0,0.0,0.0,1,13.0,0.0,0.0,1.0,1.0,1.0
18904,zuberbi01,23307,13,224,229,10,31,4,5,0,11.0,0.0,0.0,10,66.0,0.0,0.0,20.0,0.0,8.0
18905,zuberjo01,3994,2,68,136,13,34,7,1,3,16.0,1.0,0.0,12,20.0,1.0,1.0,1.0,1.0,4.0
18906,zuletju01,4001,2,79,174,24,43,11,0,9,36.0,0.0,2.0,10,51.0,1.0,6.0,0.0,1.0,5.0
18907,zumayjo01,10040,5,171,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
18908,zuninmi01,8058,4,350,1125,117,219,43,2,50,133.0,1.0,4.0,75,404.0,1.0,31.0,8.0,8.0,23.0
18909,zupcibo01,9964,6,319,795,99,199,47,4,7,80.0,7.0,5.0,57,137.0,3.0,6.0,20.0,8.0,15.0
18910,zupofr01,5876,3,16,18,3,3,1,0,0,0.0,0.0,0.0,2,6.0,0.0,0.0,0.0,0.0,0.0
18911,zuvelpa01,17875,9,209,491,41,109,17,2,2,20.0,2.0,0.0,34,50.0,1.0,2.0,18.0,0.0,8.0
18912,zuverge01,19551,12,266,142,5,21,2,1,0,7.0,0.0,1.0,9,39.0,0.0,0.0,16.0,0.0,3.0
18913,zwilldu01,7655,4,366,1280,167,364,76,15,30,202.0,46.0,0.0,128,139.0,0.0,4.0,31.0,0.0,0.0
18914,zychto01,4031,2,25,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [190]:
#####
# Creating a new column called 'xb' which is total extra base hits is the sum of dubles (2B) & Triples (3B)
# To reduce autocorrelation in regression model

In [191]:
battingdata['XB'] = battingdata['2B'] + battingdata['3B']

In [192]:
battingdata.head(50)

,playerID,yearID,stint,G,AB,R,H,2B,3B,HR,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,XB
0,aardsda01,18084,9,331,4,0,0,0,0,0,...,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0,0
1,aaronha01,45195,23,3298,12364,2174,3771,624,98,755,...,240.0,73.0,1402,1383.0,293.0,32.0,21.0,121.0,328.0,722
2,aaronto01,13768,7,437,944,102,216,42,6,13,...,9.0,8.0,86,145.0,3.0,0.0,9.0,6.0,36.0,48
3,aasedo01,25786,13,448,5,0,0,0,0,0,...,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0,0
4,abadan01,6010,3,15,21,1,2,0,0,0,...,0.0,1.0,4,5.0,0.0,0.0,0.0,0.0,1.0,0
5,abadfe01,16107,9,315,9,0,1,0,0,0,...,0.0,0.0,0,5.0,0.0,0.0,0.0,0.0,1.0,0
6,abadijo01,3750,3,12,49,4,11,0,0,0,...,1.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0,0
7,abbated01,19051,11,855,3044,355,772,99,43,11,...,142.0,0.0,289,16.0,0.0,33.0,93.0,0.0,0.0,142
8,abbeybe01,11365,7,79,225,21,38,3,3,0,...,3.0,0.0,21,54.0,0.0,0.0,4.0,0.0,0.0,6
9,abbeych01,9475,5,451,1751,307,492,67,46,19,...,93.0,0.0,167,105.0,0.0,23.0,18.0,0.0,0.0,113
10,abbotda01,1890,1,3,7,0,1,0,1,0,...,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1
11,abbotfr01,5712,3,160,513,48,107,21,6,1,...,14.0,0.0,19,0.0,0.0,8.0,20.0,0.0,0.0,27
12,abbotgl01,23743,13,248,0,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
13,abbotje01,9995,5,233,596,82,157,33,2,18,...,6.0,5.0,38,91.0,2.0,3.0,5.0,7.0,12.0,35
14,abbotji01,21932,12,263,21,0,2,0,0,0,...,0.0,0.0,0,10.0,0.0,0.0,3.0,0.0,1.0,0
15,abbotku01,19971,11,702,2044,273,523,109,23,62,...,22.0,11.0,133,571.0,11.0,17.0,21.0,12.0,37.0,132
16,abbotky01,7974,4,57,31,2,3,1,0,0,...,0.0,0.0,1,19.0,0.0,0.0,6.0,0.0,0.0,1
17,abbotod01,1910,1,22,70,2,13,2,1,0,...,3.0,0.0,6,20.0,0.0,0.0,6.0,0.0,0.0,3
18,abbotpa01,23977,13,162,20,2,5,1,0,0,...,0.0,0.0,0,6.0,0.0,0.0,5.0,0.0,0.0,1
19,aberal01,15635,10,168,100,5,14,0,0,0,...,0.0,0.0,8,41.0,0.0,0.0,8.0,1.0,2.0,0
20,abercda01,1871,1,1,4,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
21,abercre01,6021,3,180,386,65,86,20,2,9,...,18.0,8.0,21,123.0,2.0,7.0,5.0,2.0,3.0,22
22,abernbi01,1952,1,1,1,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
23,abernbr01,10014,6,232,868,97,212,36,5,8,...,21.0,7.0,60,93.0,1.0,7.0,16.0,4.0,15.0,41
24,abernte01,5829,3,7,5,0,1,0,0,0,...,0.0,0.0,1,3.0,0.0,0.0,0.0,0.0,0.0,0
25,abernte02,33409,21,681,181,12,25,3,0,0,...,0.0,0.0,6,74.0,0.0,2.0,15.0,0.0,4.0,3
26,abernwo01,3893,2,16,8,0,0,0,0,0,...,0.0,0.0,0,4.0,0.0,0.0,0.0,0.0,0.0,0
27,aberscl01,5844,3,63,179,25,45,7,3,5,...,0.0,0.0,25,44.0,0.0,0.0,0.0,0.0,6.0,10
28,ablesha01,5725,3,14,26,0,0,0,0,0,...,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
29,abnersh01,13928,8,392,840,89,191,39,4,11,...,6.0,8.0,43,153.0,10.0,7.0,5.0,7.0,14.0,43
30,abramca01,19526,12,567,1611,257,433,64,19,32,...,12.0,18.0,304,290.0,2.0,7.0,16.0,4.0,22.0,83
31,abramge01,1923,1,3,1,0,1,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
32,abregjo01,1985,1,6,9,0,0,0,0,0,...,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0,0
33,abreubo01,40100,22,2425,8480,1453,2470,574,59,288,...,400.0,128.0,1476,1840.0,115.0,33.0,7.0,85.0,165.0,633
34,abreujo01,1942,1,9,28,4,6,1,0,1,...,0.0,0.0,4,4.0,0.0,0.0,0.0,0.0,1.0,1
35,abreujo02,6045,3,458,1793,235,537,101,6,91,...,3.0,3.0,137,396.0,33.0,41.0,0.0,14.0,51.0,107
36,abreuju01,2011,1,7,0,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
37,abreuto01,12065,6,224,579,61,147,39,6,6,...,2.0,4.0,22,116.0,2.0,5.0,1.0,8.0,20.0,45
38,abreuwi01,8031,5,38,2,0,0,0,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0
39,abstebi01,5725,3,170,619,54,150,22,10,1,...,21.0,0.0,29,0.0,0.0,4.0,29.0,0.0,0.0,32
40,accarje01,20086,12,262,7,0,1,0,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0
41,aceveal01,14077,7,204,2,0,0,0,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0
42,acevejo01,10015,5,104,101,2,8,2,0,0,...,0.0,0.0,5,61.0,0.0,1.0,12.0,1.0,2.0,2
43,aceveju01,19999,12,367,65,4,6,2,0,0,...,0.0,0.0,3,33.0,0.0,0.0,6.0,0.0,2.0,2
44,achteaj01,6045,3,45,0,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
45,ackerji01,23850,14,467,54,2,9,1,0,0,...,0.0,0.0,2,32.0,0.0,0.0,0.0,0.0,1.0,1
46,ackerto01,7830,4,153,77,10,5,0,0,0,...,0.0,0.0,12,46.0,0.0,1.0,6.0,0.0,1.0,0
47,ackledu01,14096,8,635,2125,261,512,94,18,46,...,31.0,12.0,194,419.0,10.0,5.0,11.0,12.0,25.0,112
48,acklefr01,3927,2,5,6,0,2,1,0,0,...,0.0,0.0,1,4.0,0.0,0.0,0.0,0.0,0.0,1
49,acostcy01,7894,4,107,7,0,0,0,0,0,...,0.0,0.0,0,6.0,0.0,0.0,0.0,0.0,0.0,0

In [193]:
battingdata

,playerID,yearID,stint,G,AB,R,H,2B,3B,HR,...,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,XB
0,aardsda01,18084,9,331,4,0,0,0,0,0,...,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0,0
1,aaronha01,45195,23,3298,12364,2174,3771,624,98,755,...,240.0,73.0,1402,1383.0,293.0,32.0,21.0,121.0,328.0,722
2,aaronto01,13768,7,437,944,102,216,42,6,13,...,9.0,8.0,86,145.0,3.0,0.0,9.0,6.0,36.0,48
3,aasedo01,25786,13,448,5,0,0,0,0,0,...,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0,0
4,abadan01,6010,3,15,21,1,2,0,0,0,...,0.0,1.0,4,5.0,0.0,0.0,0.0,0.0,1.0,0
5,abadfe01,16107,9,315,9,0,1,0,0,0,...,0.0,0.0,0,5.0,0.0,0.0,0.0,0.0,1.0,0
6,abadijo01,3750,3,12,49,4,11,0,0,0,...,1.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0,0
7,abbated01,19051,11,855,3044,355,772,99,43,11,...,142.0,0.0,289,16.0,0.0,33.0,93.0,0.0,0.0,142
8,abbeybe01,11365,7,79,225,21,38,3,3,0,...,3.0,0.0,21,54.0,0.0,0.0,4.0,0.0,0.0,6
9,abbeych01,9475,5,451,1751,307,492,67,46,19,...,93.0,0.0,167,105.0,0.0,23.0,18.0,0.0,0.0,113
10,abbotda01,1890,1,3,7,0,1,0,1,0,...,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1
11,abbotfr01,5712,3,160,513,48,107,21,6,1,...,14.0,0.0,19,0.0,0.0,8.0,20.0,0.0,0.0,27
12,abbotgl01,23743,13,248,0,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
13,abbotje01,9995,5,233,596,82,157,33,2,18,...,6.0,5.0,38,91.0,2.0,3.0,5.0,7.0,12.0,35
14,abbotji01,21932,12,263,21,0,2,0,0,0,...,0.0,0.0,0,10.0,0.0,0.0,3.0,0.0,1.0,0
15,abbotku01,19971,11,702,2044,273,523,109,23,62,...,22.0,11.0,133,571.0,11.0,17.0,21.0,12.0,37.0,132
16,abbotky01,7974,4,57,31,2,3,1,0,0,...,0.0,0.0,1,19.0,0.0,0.0,6.0,0.0,0.0,1
17,abbotod01,1910,1,22,70,2,13,2,1,0,...,3.0,0.0,6,20.0,0.0,0.0,6.0,0.0,0.0,3
18,abbotpa01,23977,13,162,20,2,5,1,0,0,...,0.0,0.0,0,6.0,0.0,0.0,5.0,0.0,0.0,1
19,aberal01,15635,10,168,100,5,14,0,0,0,...,0.0,0.0,8,41.0,0.0,0.0,8.0,1.0,2.0,0
20,abercda01,1871,1,1,4,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
21,abercre01,6021,3,180,386,65,86,20,2,9,...,18.0,8.0,21,123.0,2.0,7.0,5.0,2.0,3.0,22
22,abernbi01,1952,1,1,1,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
23,abernbr01,10014,6,232,868,97,212,36,5,8,...,21.0,7.0,60,93.0,1.0,7.0,16.0,4.0,15.0,41
24,abernte01,5829,3,7,5,0,1,0,0,0,...,0.0,0.0,1,3.0,0.0,0.0,0.0,0.0,0.0,0
25,abernte02,33409,21,681,181,12,25,3,0,0,...,0.0,0.0,6,74.0,0.0,2.0,15.0,0.0,4.0,3
26,abernwo01,3893,2,16,8,0,0,0,0,0,...,0.0,0.0,0,4.0,0.0,0.0,0.0,0.0,0.0,0
27,aberscl01,5844,3,63,179,25,45,7,3,5,...,0.0,0.0,25,44.0,0.0,0.0,0.0,0.0,6.0,10
28,ablesha01,5725,3,14,26,0,0,0,0,0,...,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
29,abnersh01,13928,8,392,840,89,191,39,4,11,...,6.0,8.0,43,153.0,10.0,7.0,5.0,7.0,14.0,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18885,zimmejo02,16100,8,200,324,18,55,6,0,1,...,0.0,0.0,10,99.0,0.0,0.0,44.0,2.0,2.0,6
18886,zimmero01,1945,1,27,98,14,27,1,0,5,...,1.0,0.0,5,16.0,0.0,3.0,0.0,0.0,2.0,1
18887,zimmery01,24126,12,1408,5416,793,1505,338,20,215,...,41.0,15.0,539,1087.0,41.0,25.0,1.0,58.0,173.0,358
18888,zinkch01,2008,1,1,0,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
18889,zinkwa01,1921,1,2,1,0,0,0,0,0,...,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0
18890,zinnfr01,1888,1,2,7,0,0,0,0,0,...,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0
18891,zinngu01,9565,5,314,1103,136,297,51,23,15,...,28.0,0.0,109,77.0,0.0,6.0,29.0,0.0,0.0,74
18892,zinnji01,9611,5,76,120,17,34,6,2,2,...,2.0,1.0,7,18.0,0.0,1.0,3.0,0.0,0.0,8
18893,zinsebi01,1944,1,2,0,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
18894,zinteal01,4006,2,67,78,7,13,4,0,3,...,0.0,0.0,5,34.0,0.0,0.0,0.0,1.0,0.0,4
18895,zipfebu01,3923,2,118,354,38,78,11,6,10,...,2.0,3.0,32,92.0,1.0,1.0,4.0,2.0,4.0,17
18896,ziskri01,25701,13,1453,5144,681,1477,245,26,207,...,8.0,15.0,533,910.0,52.0,12.0,7.0,41.0,138.0,271
18897,zitoba01,30106,15,434,344,12,35,0,0,0,...,0.0,0.0,18,99.0,0.0,0.0,56.0,0.0,4.0,0
18898,zitzmbi01,13473,8,406,1004,197,268,38,11,3,...,42.0,11.0,83,85.0,0.0,16.0,39.0,0.0,0.0,49
18899,zmiched01,3821,2,13,17,0,1,0,0,0,...,0.0,0.0,0,10.0,0.0,0.0,0.0,0.0,0.0,0
18900,zobribe01,24136,13,1337,4840,735,1287,296,38,145,...,111.0,43.0,700,839.0,32.0,26.0,23.0,55.0,97.0,334
18901,zoccope01,2003,1,20,37,0,4,1,0,0,...,0.0,0.0,2,13.0,0.0,0.0,0.0,0.0,1.0,1
18902,zoldasa01,19480,11,251,286,16,50,6,0,0,...,1.0,0.0,10,52.0,0.0,1.0,9.0,0.0,4.0,6
18903,zoskyed01,9977,5,44,50,4,8,1,2,0,...,0.0,0.0,1,13.0,0.0,0.0,1.0,1.0,1.0,3
18904,zuberbi01,23307,13,224,229,10,31,4,5,0,...,0.0,0.0,10,66.0,0.0,0.0,20.0,0.0,8.0,9
18905,zuberjo01,3994,2,68,136,13,34,7,1,3,...,1.0,0.0,12,20.0,1.0,1.0,1.0,1.0,4.0,8
18906,zuletju01,4001,2,79,174,24,43,11,0,9,...,0.0,2.0,10,51.0,1.0,6.0,0.0,1.0,5.0,11
18907,zumayjo01,10040,5,171,0,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0
18908,zuninmi01,8058,4,350,1125,117,219,43,2,50,...,1.0,4.0,75,404.0,1.0,31.0,8.0,8.0,23.0,45
18909,zupcibo01,9964,6,319,795,99,199,47,4,7,...,7.0,5.0,57,137.0,3.0,6.0,20.0,8.0,15.0,51
18910,zupofr01,5876,3,16,18,3,3,1,0,0,...,0.0,0.0,2,6.0,0.0,0.0,0.0,0.0,0.0,1
18911,zuvelpa01,17875,9,209,491,41,109,17,2,2,...,2.0,0.0,34,50.0,1.0,2.0,18.0,0.0,8.0,19
18912,zuverge01,19551,12,266,142,5,21,2,1,0,...,0.0,1.0,9,39.0,0.0,0.0,16.0,0.0,3.0,3
18913,zwilldu01,7655,4,366,1280,167,364,76,15,30,...,46.0,0.0,128,139.0,0.0,4.0,31.0,0.0,0.0,91
18914,zychto01,4031,2,25,0,0,0,0,0,0,...,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0

In [194]:
battingdata.dtypes

playerID     object
yearID        int64
stint         int64
G             int64
AB            int64
R             int64
H             int64
2B            int64
3B            int64
HR            int64
RBI         float64
SB          float64
CS          float64
BB            int64
SO          float64
IBB         float64
HBP         float64
SH          float64
SF          float64
GIDP        float64
XB            int64
dtype: object